Chart.defaults.color = '#475569';
Chart.defaults.font.family = 'Inter, system-ui, -apple-system, sans-serif';
Chart.defaults.font.size = 12;
Chart.defaults.plugins.tooltip.backgroundColor = '#0f172a';
Chart.defaults.plugins.tooltip.borderColor = '#1e293b';
Chart.defaults.plugins.tooltip.borderWidth = 1;
Chart.defaults.plugins.tooltip.titleFont = { weight: '600', size: 13 };
Chart.defaults.plugins.tooltip.bodyFont = { size: 12 };
Chart.defaults.plugins.tooltip.padding = 10;
Chart.defaults.scale.grid.color = '#e2e8f0';
Chart.defaults.scale.ticks.color = '#475569';

function switchTab(id, btn) {
  document.querySelectorAll('.tab').forEach(t => {
    t.classList.remove('active');
    t.setAttribute('aria-selected', 'false');
  });
  document.querySelectorAll('.panel').forEach(p => p.classList.remove('active'));
  document.getElementById('tab-' + id).classList.add('active');
  btn.classList.add('active');
  btn.setAttribute('aria-selected', 'true');
}
window.switchTab = switchTab;

// ─── AUTO-GENERATED FROM: MVLOAD_26_07_2026.xlsx ───────────────────────────
// Report Date : July 26, 2026 (revised pull — same day as the previous file, updated totals)
// Generated by MVIKAS Dashboard Processor

// NOTE: Monthly targets loaded from Tonnage_of_June_Month sheet (contains July 2026 target columns)
// Achieved = tonnage dispatched so far this month, from Total_Tonnage_this_month sheet (July 2026)
// Global Impex and Grover Innovations LLP no longer appear anywhere in this file and have been removed.

const clients = [
  { name: 'Carrier Refrigeration',           person: 'Sangeet Dhasmana',  target: 293072.82, achieved: 210033.85, activeDays: 26 },
  { name: 'Bombax',                          person: 'Sangeet Dhasmana',  target: 97357.44,  achieved: 92848.4,   activeDays: 26 },
  { name: 'Carrier CTD',                     person: 'Deepak Sharma',     target: 29784.07,  achieved: 86500.47,  activeDays: 26 },
  { name: 'Haier CCR',                       person: 'Deepak Sharma',     target: 0,         achieved: 3615.04,   activeDays: 26 },
  { name: 'Loom Solar Pvt Ltd',              person: 'Deepak Sharma',     target: 14457.83,  achieved: 14523.0,   activeDays: 26 },
  { name: 'Kumar Services',                  person: 'Deepak Sharma',     target: 13725.49,  achieved: 13378.56,  activeDays: 26 },
  { name: 'Sukuga Technologies Pvt Ltd',     person: 'Deepak Sharma',     target: 10141.99,  achieved: 12127.74,  activeDays: 26 },
  { name: 'Cosmos Pumps Pvt Ltd',            person: 'Deepak Sharma',     target: 11398.18,  achieved: 5366.88,   activeDays: 26 },
  { name: 'Oneiric Appliances Pvt Ltd',      person: 'Deepak Sharma',     target: 15232.29,  achieved: 8420.4,    activeDays: 26 },
  { name: 'Paramount Surgimed Ltd',          person: 'Deepak Sharma',     target: 12038.52,  achieved: 6131.71,   activeDays: 26 },
  { name: 'Medical Science',                 person: 'Sangeet Dhasmana',  target: 6013.75,   achieved: 3263.99,   activeDays: 26 },
  { name: 'Mitras Technocrafts Pvt Ltd',     person: 'Deepak Sharma',     target: 13501.35,  achieved: 2458.39,   activeDays: 26 },
  { name: 'Vaidrishi Laboratories Pvt Ltd',  person: 'Sangeet Dhasmana',  target: 0,         achieved: 1933.74,   activeDays: 26 },
  { name: 'Frick India',                     person: 'Deepak Sharma',     target: 0,         achieved: 0,         activeDays: 26 },
  { name: 'Indu Sports',                     person: 'Sangeet Dhasmana',  target: 0,         achieved: 0,         activeDays: 26 },
  { name: 'Stockarea',                       person: 'Deepak Sharma',     target: 0,         achieved: 0,         activeDays: 26 },
  { name: 'Edusoft Healthcare Ltd',          person: 'Deepak Sharma',     target: 3631.08,   achieved: 0,         activeDays: 26 },
  { name: 'GCPA',                            person: 'Shiva',             target: 0,         achieved: 0,         activeDays: 26 },
  { name: 'Pangea',                          person: 'Deepak Sharma',     target: 9090.91,   achieved: 0,         activeDays: 26 },
  { name: 'RSR',                             person: 'Deepak Sharma',     target: 5000,      achieved: 0,         activeDays: 26, isNew: true },
  { name: 'Epson',                           person: 'Sangeet Dhasmana',  target: 10000,     achieved: 3271.96,   activeDays: 26, isNew: true },
  { name: 'KRF',                             person: 'Not Alloted',       target: 0,         achieved: 0,         activeDays: 26, isNew: true },
  { name: 'Conficore',                       person: 'Deepak Sharma',  target: 5000,      achieved: 445.0,     activeDays: 26, isNew: true },
  { name: 'KTB',                             person: 'Sangeet Dhasmana',  target: 0,         achieved: 1014.03,   activeDays: 26 },
  { name: 'MV-Zenotel',                      person: 'Sangeet Dhasmana',  target: 0,         achieved: 80.0,      activeDays: 26 },
];

clients.forEach(c => {
  c.pct = c.target > 0 ? Math.round(c.achieved / c.target * 100) : (c.achieved > 0 ? 999 : 0);
  c.avgDay = c.activeDays > 0 ? Math.round(c.achieved / c.activeDays) : 0;
  c.remaining = Math.max((c.target || 0) - c.achieved, 0);
  c.daysNeeded = c.avgDay > 0 && c.remaining > 0 ? parseFloat((c.remaining / c.avgDay).toFixed(1)) : (c.remaining === 0 ? 0 : 999);
});

// ─── 10-DAY PERIOD BREAKDOWN (First 10 / Mid 10 / Last 10 days) ───────────────
// Target tonnage per period, read directly from the sheet's own
// "First/Mid/Last 10 days Target (kg)" columns (MVLOAD_24_07_2026.xlsx).
const periodTarget = {
  'Carrier Refrigeration':           { first10: 92317.94, mid10: 87921.85, last10: 114298.4 },
  'Carrier CTD':                     { first10: 11466.87, mid10: 10126.58, last10: 8339.538 },
  'Mitras Technocrafts Pvt Ltd':     { first10: 4117.912, mid10: 4927.993, last10: 4387.939 },
  'Paramount Surgimed Ltd':          { first10: 1083.467, mid10: 2166.934, last10: 8788.122 },
  'Haier CCR':                       { first10: null, mid10: null, last10: null },
  'Bombax':                          { first10: 30180.81, mid10: 37482.61, last10: 29207.23 },
  'Global Impex':                    { first10: null, mid10: null, last10: null },
  'Kumar Services':                  { first10: 4598.039, mid10: 5421.569, last10: 3637.255 },
  'Edusoft Healthcare Ltd':          { first10: 2904.866, mid10: 726.2164, last10: 0.0 },
  'Oneiric Appliances Pvt Ltd':      { first10: 6626.047, mid10: 4112.719, last10: 4493.526 },
  'Vaidrishi Laboratories Pvt Ltd':  { first10: null, mid10: null, last10: null },
  'Sukuga Technologies Pvt Ltd':     { first10: 1470.588, mid10: 4665.314, last10: 4006.085 },
  'Cosmos Pumps Pvt Ltd':            { first10: 3647.416, mid10: 4331.307, last10: 3362.462 },
  'Loom Solar Pvt Ltd':              { first10: 4192.771, mid10: 4481.928, last10: 5783.133 },
  'GCPA':                            { first10: null, mid10: null, last10: null },
  'Pangea':                          { first10: 3030.303, mid10: 3030.303, last10: 3030.303 },
  'RSR':                             { first10: 1666.667, mid10: 1666.667, last10: 1666.667 },
  'Medical Science':                 { first10: 0.0, mid10: 1924.399, last10: 4089.347 },
  'Epson':                           { first10: 3333.333, mid10: 3333.333, last10: 3333.333 },
  'KRF':                             { first10: null, mid10: null, last10: null },
  'Frick India':                     { first10: null, mid10: null, last10: null },
  'Indu Sports':                     { first10: null, mid10: null, last10: null },
  'Conficore':                       { first10: 1666.667, mid10: 1666.667, last10: 1666.667 },
  'KTB':                             { first10: null, mid10: null, last10: null },
  'MV-Zenotel':                      { first10: null, mid10: null, last10: null },
};

// Achieved tonnage per period — day-wise figures from the Tonnage_of_June_Month sheet
// (MVLOAD_26_07_2026.xlsx), summed for days 1-10, 11-20, and 21-31 per customer.
// This is a revised pull for the same date (July 26) with updated day-wise totals for
// several customers vs. the earlier same-day file (notably Carrier CTD, Medical Science, Haier CCR).
const periodAchieved = {
  'Carrier Refrigeration':           { first10: 56904.0, mid10: 73480.32, last10: 79279.93 },
  'Carrier CTD':                     { first10: 26677.05, mid10: 36193.39, last10: 23589.65 },
  'Mitras Technocrafts Pvt Ltd':     { first10: 935.01, mid10: 522.0, last10: 1001.38 },
  'Paramount Surgimed Ltd':          { first10: null, mid10: 1333.0, last10: 4798.71 },
  'Haier CCR':                       { first10: 3033.0, mid10: null, last10: 581.0 },
  'Bombax':                          { first10: 37481.48, mid10: 36134.29, last10: 19231.7 },
  'Kumar Services':                  { first10: 4114.98, mid10: 4523.15, last10: 4740.36 },
  'Edusoft Healthcare Ltd':          { first10: null, mid10: null, last10: null },
  'Oneiric Appliances Pvt Ltd':      { first10: 5429.2, mid10: 1042.2, last10: 1949.0 },
  'Vaidrishi Laboratories Pvt Ltd':  { first10: 750.0, mid10: 981.95, last10: 201.79 },
  'Sukuga Technologies Pvt Ltd':     { first10: 4604.3, mid10: 3659.01, last10: 3862.58 },
  'Cosmos Pumps Pvt Ltd':            { first10: 4249.9, mid10: 860.0, last10: 256.98 },
  'Loom Solar Pvt Ltd':              { first10: 900.0, mid10: 8533.0, last10: 3070.0 },
  'GCPA':                            { first10: null, mid10: null, last10: null },
  'Pangea':                          { first10: null, mid10: null, last10: null },
  'RSR':                             { first10: null, mid10: null, last10: null },
  'Medical Science':                 { first10: null, mid10: 120.0, last10: 3143.99 },
  'Epson':                           { first10: 1584.8, mid10: 1260.04, last10: 354.08 },
  'KRF':                             { first10: null, mid10: null, last10: null },
  'Frick India':                     { first10: null, mid10: null, last10: null },
  'Indu Sports':                     { first10: null, mid10: null, last10: null },
  'Conficore':                       { first10: 445.0, mid10: null, last10: null },
  'KTB':                             { first10: 1014.03, mid10: null, last10: null },
  'MV-Zenotel':                      { first10: 80.0, mid10: null, last10: null },
};


clients.forEach(c => {
  const t = periodTarget[c.name];
  const a = periodAchieved[c.name];
  c.periods = {
    first10: { target: t ? t.first10 : null, achieved: a ? a.first10 : null },
    mid10:   { target: t ? t.mid10   : null, achieved: a ? a.mid10   : null },
    last10:  { target: t ? t.last10  : null, achieved: a ? a.last10  : null },
  };
});

// Customer-level counts, matching the real 'Order EDD Crossed' sheet (108 orders, as of July 26, 2026)
const eddData = [
  { name: 'Carrier Refrigeration',  count: 48  },
  { name: 'Bombax',                 count: 35  },
  { name: 'Loom Solar',             count: 5   },
  { name: 'Oneric Appliances',      count: 4   },
  { name: 'MITRAS',                 count: 4   },
  { name: 'Carrier - CTD',          count: 4   },
  { name: 'Epson India',            count: 3   },
  { name: 'Kumar Services',         count: 2   },
  { name: 'Medical Science',        count: 2   },
  { name: 'Paramount Surgimed Ltd', count: 1   },
];
const eddTotal = eddData.reduce((a, b) => a + b.count, 0);

// ─── EDD CROSSED — per-order detail (drill-down panel) ────────────────────────
// Sourced from the 'Order EDD Crossed' sheet: Order_id, Customername, TransporterName, EDD, DelayReason
const eddDetail = [
  { id:"MVS/26-27/4080", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"02 Jun 2026", reason:"Damaged Consignment / Refused by Customer" },
  { id:"MVS/26-27/5992", name:"Paramount Surgimed Ltd", transporter:"GATI", edd:"01 Jul 2026", reason:"Delayed \u2013 Misrouted Shipment" },
  { id:"MVS/26-27/6589", name:"Bombax", transporter:"EKART", edd:"03 Jul 2026", reason:"Space Issue at Customer Place" },
  { id:"MVS/26-27/6675", name:"Bombax", transporter:"EKART", edd:"06 Jul 2026", reason:"On Hold \u2013 Refused By Customer" },
  { id:"MVS/26-27/7450", name:"Bombax", transporter:"DP WORLD", edd:"12 Jul 2026", reason:"Delayed - Space Issue At Customer Place" },
  { id:"MVS/26-27/7468", name:"Bombax", transporter:"DP WORLD", edd:"15 Jul 2026", reason:"On Hold \u2013 Refused By Customer" },
  { id:"MVS/26-27/7866", name:"Bombax", transporter:"EKART", edd:"20 Jul 2026", reason:"On Hold \u2013 Refused By Customer" },
  { id:"MVS/26-27/8153", name:"Bombax", transporter:"EKART", edd:"23 Jul 2026", reason:"Hub-to-hub transit delay" },
  { id:"MVS/26-27/8282", name:"Bombax", transporter:"EKART", edd:"20 Jul 2026", reason:null },
  { id:"MVS/26-27/8398", name:"Epson India", transporter:"EKART", edd:"22 Jul 2026", reason:"Delayed Natural Calamity" },
  { id:"MVS/26-27/8524", name:"Oneric Appliances", transporter:"EKART", edd:"22 Jul 2026", reason:"Delayed \u2013 ODA/Remote Location" },
  { id:"MVS/26-27/8575", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"25 Jul 2026", reason:"Delayed - Alternate Contact Required" },
  { id:"MVS/26-27/8698", name:"Carrier Refrigeration", transporter:"EKART", edd:"24 Jul 2026", reason:null },
  { id:"MVS/26-27/8740", name:"Kumar Services", transporter:"DP WORLD", edd:"24 Jul 2026", reason:"Delayed \u2013 Natural Calamity" },
  { id:"MVS/26-27/8742", name:"MITRAS", transporter:"DP WORLD", edd:"24 Jul 2026", reason:null },
  { id:"MVS/26-27/8784", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"25 Jul 2026", reason:null },
  { id:"MVS/26-27/8793", name:"Carrier Refrigeration", transporter:"EKART", edd:"25 Jul 2026", reason:null },
  { id:"MVS/26-27/9033", name:"Carrier Refrigeration", transporter:"EKART", edd:"25 Jul 2026", reason:null },
  { id:"MVS/26-27/2694", name:"Bombax", transporter:"EKART", edd:"19 May 2026", reason:"Customer refused to accept" },
  { id:"MVS/26-27/2900", name:"Bombax", transporter:"EKART", edd:"22 May 2026", reason:"RTO (Documents are Pending) / Store Closed" },
  { id:"MVS/26-27/6865", name:"Bombax", transporter:"DP WORLD", edd:"10 Jul 2026", reason:"Hold By Consignee/ Consignor" },
  { id:"MVS/26-27/7103", name:"Bombax", transporter:"EKART", edd:"11 Jul 2026", reason:"Connection Was delayed due to Rain" },
  { id:"MVS/26-27/7138", name:"Bombax", transporter:"DP World", edd:"10 Jul 2026", reason:"Delayed - Space Issue At Customer Place" },
  { id:"MVS/26-27/8462", name:"Carrier Refrigeration", transporter:"EKART / REVERSE", edd:"19 Jul 2026", reason:"Delayed \u2013 Address Verification Required" },
  { id:"MVS/26-27/8484", name:"Loom Solar", transporter:"GATI", edd:"25 Jul 2026", reason:null },
  { id:"MVS/26-27/8531", name:"Carrier Refrigeration", transporter:"EKART", edd:"25 Jul 2026", reason:null },
  { id:"MVS/26-27/8707", name:"Carrier Refrigeration", transporter:"EKART", edd:"24 Jul 2026", reason:null },
  { id:"MVS/26-27/8909", name:"MITRAS", transporter:"DP WORLD", edd:"25 Jul 2026", reason:"Delayed - Alternate Contact Required" },
  { id:"MVS/26-27/2692", name:"Bombax", transporter:"EKART", edd:"19 May 2026", reason:"RTO (Documents are Pending) / Store Closed" },
  { id:"MVS/26-27/2698", name:"Bombax", transporter:"EKART", edd:"19 May 2026", reason:"Refused by Consignee" },
  { id:"MVS/26-27/6806", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"06 Jul 2026", reason:"Vendor Delay - PO Expired" },
  { id:"MVS/26-27/7560", name:"Bombax", transporter:"EKART", edd:"17 Jul 2026", reason:"vendor Delay - Intransit Delay" },
  { id:"MVS/26-27/8324", name:"Carrier Refrigeration", transporter:"EKART", edd:"20 Jul 2026", reason:"Incorrect or incomplete documentation" },
  { id:"MVS/26-27/8423", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"21 Jul 2026", reason:null },
  { id:"MVS/26-27/8661", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"25 Jul 2026", reason:"Delayed \u2013 Natural Calamity" },
  { id:"MVS/26-27/8852", name:"Carrier - CTD", transporter:"EKART", edd:"25 Jul 2026", reason:null },
  { id:"MVS/26-27/9034", name:"Carrier Refrigeration", transporter:"EKART", edd:"25 Jul 2026", reason:null },
  { id:"MVS/26-27/6780", name:"MITRAS", transporter:"DELHIVERY", edd:"04 Jul 2026", reason:"Delayed in Hub Transit" },
  { id:"MVS/26-27/7796", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"18 Jul 2026", reason:"Delayed \u2013 Sez Delivery" },
  { id:"MVS/26-27/8033", name:"Bombax", transporter:"DP WORLD", edd:"23 Jul 2026", reason:"Delayed - Consignee not available" },
  { id:"MVS/26-27/8064", name:"Bombax", transporter:"DP WORLD", edd:"23 Jul 2026", reason:"Hold By Consignee/ Consignor(8891203387)" },
  { id:"MVS/26-27/8194", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"20 Jul 2026", reason:"Delayed - Alternate Contact Required" },
  { id:"MVS/26-27/8209", name:"Carrier Refrigeration", transporter:"DP WORLD", edd:"20 Jul 2026", reason:"Hold By Consignee/ Consignor" },
  { id:"MVS/26-27/8296", name:"Bombax", transporter:"EKART", edd:"24 Jul 2026", reason:"Delayed - Space Issue At Customer Place" },
  { id:"MVS/26-27/8446", name:"Carrier Refrigeration", transporter:"EKART", edd:"21 Jul 2026", reason:"Delayed \u2013 ODA/Remote Location" },
  { id:"MVS/26-27/8464", name:"Carrier Refrigeration", transporter:"EKART / REVERSE", edd:"19 Jul 2026", reason:"On Hold \u2013 Refused By Customer" },
  { id:"MVS/26-27/8485", name:"Loom Solar", transporter:"GATI", edd:"25 Jul 2026", reason:null },
  { id:"MVS/26-27/8612", name:"Kumar Services", transporter:"DP WORLD", edd:"23 Jul 2026", reason:"Delayed \u2013 Natural Calamity" },
  { id:"MVS/26-27/8669", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"25 Jul 2026", reason:"Delayed \u2013 Natural Calamity" },
  { id:"MVS/26-27/8773", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"25 Jul 2026", reason:null },
  { id:"MVS/26-27/8779", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"25 Jul 2026", reason:null },
  { id:"MVS/26-27/9018", name:"Medical Science", transporter:"LAST MILE", edd:"25 Jul 2026", reason:null },
  { id:"MVS/26-27/1304", name:"Bombax", transporter:"EKART", edd:"28 Apr 2026", reason:"DEPS" },
  { id:"MVS/26-27/4353", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"05 Jun 2026", reason:null },
  { id:"MVS/26-27/7136", name:"Bombax", transporter:"DP World", edd:"10 Jul 2026", reason:"Delayed - Space Issue At Customer Place" },
  { id:"MVS/26-27/7333", name:"Bombax", transporter:"DP WORLD", edd:"13 Jul 2026", reason:"On Hold \u2013 Refused By Customer(Mr Shubham -77190270..." },
  { id:"MVS/26-27/7872", name:"Bombax", transporter:"EKART", edd:"20 Jul 2026", reason:"Sales Person to accept the Shipment in Shopper" },
  { id:"MVS/26-27/8129", name:"Bombax", transporter:"EKART", edd:"23 Jul 2026", reason:"Sales Person to accept the Shipment in Shopper" },
  { id:"MVS/26-27/8207", name:"Carrier Refrigeration", transporter:"DP WORLD", edd:"20 Jul 2026", reason:"Delayed \u2013 Address Verification Required" },
  { id:"MVS/26-27/8376", name:"Oneric Appliances", transporter:"DP WORLD", edd:"23 Jul 2026", reason:"Delayed \u2013 Address Verification Required" },
  { id:"MVS/26-27/8377", name:"Oneric Appliances", transporter:"DP WORLD", edd:"22 Jul 2026", reason:"Delayed - Natural Calamity" },
  { id:"MVS/26-27/8519", name:"MITRAS", transporter:"DP WORLD", edd:"21 Jul 2026", reason:null },
  { id:"MVS/26-27/8667", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"25 Jul 2026", reason:"Delayed \u2013 Missed Connection" },
  { id:"MVS/26-27/8672", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"25 Jul 2026", reason:"Delayed \u2013 Natural Calamity" },
  { id:"MVS/26-27/8948", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"25 Jul 2026", reason:null },
  { id:"MVS/26-27/2680", name:"Bombax", transporter:"EKART", edd:"19 May 2026", reason:"Premises Closed /Not Operational" },
  { id:"MVS/26-27/2684", name:"Bombax", transporter:"EKART", edd:"17 May 2026", reason:"RTO (Documents are Pending)" },
  { id:"MVS/26-27/2764", name:"Bombax", transporter:"EKART", edd:"20 May 2026", reason:"RTO (Documents are Pending) / Store Closed" },
  { id:"MVS/26-27/2874", name:"Bombax", transporter:"EKART", edd:"24 May 2026", reason:"RTO (Documents are Pending) / Store Closed" },
  { id:"MVS/26-27/7283", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/8104", name:"Bombax", transporter:"EKART", edd:"22 Jul 2026", reason:"Hub-to-hub transit delay" },
  { id:"MVS/26-27/8250", name:"Loom Solar", transporter:null, edd:"20 Jul 2026", reason:"Delayed in Hub Transit" },
  { id:"MVS/26-27/8419", name:"Bombax", transporter:"EKART", edd:"23 Jul 2026", reason:null },
  { id:"MVS/26-27/8459", name:"Carrier Refrigeration", transporter:"EKART", edd:"21 Jul 2026", reason:"Delayed \u2013 ODA/Remote Location" },
  { id:"MVS/26-27/8463", name:"Carrier Refrigeration", transporter:"EKART / REVERSE", edd:"19 Jul 2026", reason:"Delayed Missed Connection" },
  { id:"MVS/26-27/8482", name:"Carrier Refrigeration", transporter:"EKART REVERSE", edd:"19 Jul 2026", reason:"Delayed in Hub Transit" },
  { id:"MVS/26-27/8532", name:"Carrier Refrigeration", transporter:"EKART", edd:"20 Jul 2026", reason:"Delayed \u2013 ODA/Remote Location" },
  { id:"MVS/26-27/8619", name:"Epson India", transporter:"EKART", edd:"25 Jul 2026", reason:"Delayed \u2013 Natural Calamity" },
  { id:"MVS/26-27/8633", name:"Bombax", transporter:"EKART", edd:"24 Jul 2026", reason:null },
  { id:"MVS/26-27/8756", name:"Epson India", transporter:"EKART", edd:"25 Jul 2026", reason:"On Time" },
  { id:"MVS/26-27/8863", name:"Oneric Appliances", transporter:"EKART", edd:"25 Jul 2026", reason:null },
  { id:"MVS/26-27/8937", name:"Carrier Refrigeration", transporter:"EKART", edd:"25 Jul 2026", reason:null },
  { id:"MVS/26-27/9016", name:"Medical Science", transporter:"LAST MILE", edd:"25 Jul 2026", reason:null },
  { id:"MVS/26-27/9032", name:"Carrier Refrigeration", transporter:"EKART", edd:"25 Jul 2026", reason:"Delayed \u2013 Natural Calamity" },
  { id:"MVS/26-27/8039", name:"Bombax", transporter:"DP WORLD", edd:"24 Jul 2026", reason:null },
  { id:"MVS/26-27/8159", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"22 Jul 2026", reason:"Delayed \u2013 Invalid Contact Details" },
  { id:"MVS/26-27/8175", name:"Carrier Refrigeration", transporter:"EKART", edd:"17 Jul 2026", reason:"Delayed in Hub Transit" },
  { id:"MVS/26-27/8245", name:"Bombax", transporter:"DP WORLD", edd:"24 Jul 2026", reason:null },
  { id:"MVS/26-27/8248", name:"Loom Solar", transporter:"GATI(PARCEL IT)", edd:"23 Jul 2026", reason:null },
  { id:"MVS/26-27/8261", name:"Carrier Refrigeration", transporter:"OM LOGISTIC", edd:"20 Jul 2026", reason:null },
  { id:"MVS/26-27/8364", name:"Carrier Refrigeration", transporter:"EKART", edd:"19 Jul 2026", reason:null },
  { id:"MVS/26-27/8410", name:"Carrier - CTD", transporter:"EKART", edd:"23 Jul 2026", reason:"Delayed in Hub Transit" },
  { id:"MVS/26-27/8647", name:"Bombax", transporter:"EKART", edd:"24 Jul 2026", reason:null },
  { id:"MVS/26-27/8666", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"25 Jul 2026", reason:"Delayed \u2013 Natural Calamity" },
  { id:"MVS/26-27/8762", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"25 Jul 2026", reason:"Delayed \u2013 Natural Calamity" },
  { id:"MVS/26-27/8780", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"25 Jul 2026", reason:null },
  { id:"MVS/26-27/8940", name:"Carrier Refrigeration", transporter:"EKART", edd:"25 Jul 2026", reason:null },
  { id:"MVS/26-27/2679", name:"Bombax", transporter:"EKART", edd:"17 May 2026", reason:"Refused by Consignee" },
  { id:"MVS/26-27/3032", name:"Bombax", transporter:"EKART", edd:"23 May 2026", reason:"Customer refused to accept" },
  { id:"MVS/26-27/7668", name:"Carrier - CTD", transporter:"EKART", edd:"16 Jul 2026", reason:"Delayed in Hub Transit" },
  { id:"MVS/26-27/8251", name:"Loom Solar", transporter:"GATI", edd:"25 Jul 2026", reason:null },
  { id:"MVS/26-27/8277", name:"Carrier - CTD", transporter:"EKART", edd:"22 Jul 2026", reason:"Delayed in Hub Transit" },
  { id:"MVS/26-27/8313", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"21 Jul 2026", reason:"Festival, strike, or local movement restrictions" },
  { id:"MVS/26-27/8332", name:"Carrier Refrigeration", transporter:"EKART", edd:"18 Jul 2026", reason:"Delayed \u2013 ODA/Remote Location" },
  { id:"MVS/26-27/8664", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"25 Jul 2026", reason:"Delayed \u2013 Natural Calamity" },
  { id:"MVS/26-27/8776", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"25 Jul 2026", reason:null },
  { id:"MVS/26-27/8789", name:"Carrier Refrigeration", transporter:"EKART", edd:"25 Jul 2026", reason:null },
  { id:"MVS/26-27/9061", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"25 Jul 2026", reason:"Delayed \u2013 Natural Calamity" },
];

function renderEddDetail(filterText) {
  const tbody = document.getElementById('edd-detail-body');
  const countEl = document.getElementById('edd-detail-count');
  if (!tbody) return;
  const q = (filterText || '').trim().toLowerCase();
  const rows = q
    ? eddDetail.filter(r => r.name.toLowerCase().includes(q) || r.id.toLowerCase().includes(q) || (r.transporter || '').toLowerCase().includes(q))
    : eddDetail;

  if (countEl) countEl.textContent = `${rows.length} of ${eddDetail.length} orders`;

  if (rows.length === 0) {
    tbody.innerHTML = `<tr><td colspan="5" style="text-align:center;color:#94a3b8;padding:24px">No matching orders.</td></tr>`;
    return;
  }

  tbody.innerHTML = rows.map(r => `<tr>
      <td style="font-weight:600">${r.id}</td>
      <td>${r.name}</td>
      <td>${r.transporter || '—'}</td>
      <td style="color:#dc2626;font-weight:600">${r.edd || '—'}</td>
      <td>${r.reason ? r.reason : '<span style="color:#94a3b8">Intransit Delay</span>'}</td>
    </tr>`).join('');
}
window.renderEddDetail = renderEddDetail;

// Jump from the EDD Crossed KPI card straight to the drill-down panel
function goToEddDetail() {
  const btn = document.getElementById('tab-btn-edd');
  if (btn) switchTab('edd', btn);
  const panel = document.getElementById('tab-edd');
  if (panel) panel.scrollIntoView({ behavior: 'smooth', block: 'start' });
}
window.goToEddDetail = goToEddDetail;

const openData = [
  { name: 'Carrier Refrigeration',    count: 212 },
  { name: 'Bombax',                   count: 151 },
  { name: 'Carrier - CTD',            count: 62  },
  { name: 'Sukuga',                   count: 18  },
  { name: 'Loom Solar',               count: 13  },
  { name: 'Epson India',              count: 7   },
  { name: 'Paramount Surgimed Ltd',   count: 6   },
  { name: 'MITRAS',                   count: 5   },
  { name: 'Oneric Appliances',        count: 5   },
  { name: 'Kumar Services',           count: 5   },
  { name: 'Stockarea',                count: 4   },
  { name: 'Medical Science',          count: 4   },
  { name: 'Vaidrishi Laboratories',   count: 3   },
  { name: 'MVIKAS Tech',              count: 2   },
  { name: 'Cosmos Pumps Pvt. Ltd.',   count: 2   },
  { name: 'Haier CCR',                count: 1   },
];
const openTotal = openData.reduce((a, b) => a + b.count, 0);

const dueData = [
  { name: 'Carrier Refrigeration',  count: 36 },
  { name: 'Bombax',                 count: 14 },
  { name: 'Carrier - CTD',          count: 14 },
  { name: 'Sukuga',                 count: 4  },
  { name: 'Loom Solar',             count: 2  },
  { name: 'Oneric Appliances',      count: 2  },
  { name: 'MITRAS',                 count: 2  },
  { name: 'Epson India',            count: 2  },
  { name: 'Kumar Services',         count: 1  },
  { name: 'Haier CCR',              count: 1  },
];
const dueTotal = dueData.reduce((a, b) => a + b.count, 0);

const bookedData = [
  { name: 'Oneric Appliances',      count: 5  },
  { name: 'Paramount Surgimed Ltd', count: 1  },
];
const bookedTotal = bookedData.reduce((a, b) => a + b.count, 0);

const dailyTonnageData = [
  { name: 'Oneric Appliances',      kg: 1558.00 },
  { name: 'Paramount Surgimed Ltd', kg: 350.08  },
];
const dailyTotal = dailyTonnageData.reduce((a, b) => a + b.kg, 0);

const monthlyTotal = clients.reduce((a, c) => a + c.achieved, 0);
const daysInMonth = 31; // July has 31 days
const activeDaysElapsed = 26; // through July 26, 2026 (last fully-closed day of data)
const dailyAverage = monthlyTotal / activeDaysElapsed; // avg over active days

// ─── UPDATE HEADER ─────────────────────────────────────────────────────────────
const elDate = document.querySelector('.badge-date');
const elElapsed = document.querySelector('.badge-elapsed');
if (elDate) elDate.textContent = 'As of July 26, 2026';
if (elElapsed) elElapsed.textContent = '26 / 31 days elapsed · July 2026';

// ─── UPDATE KPI CARDS ─────────────────────────────────────────────────────────
document.getElementById('kpi-open').textContent = openTotal;
document.getElementById('kpi-edd').textContent = eddTotal;
document.getElementById('kpi-edd-pct').textContent = Math.round(eddTotal / openTotal * 100) + '% of open';
renderEddDetail('');
document.getElementById('kpi-due').textContent = dueTotal;
document.getElementById('kpi-booked').textContent = bookedTotal;
try { document.getElementById('kpi-booked').closest('.metric').querySelector('.metric-sub').textContent = 'July 26, 2026'; } catch(e){}
document.getElementById('kpi-daily-ton').innerHTML = dailyTotal.toLocaleString('en-IN', { maximumFractionDigits: 2 }) + ' <span style="font-size:0.9rem;font-weight:600">kg</span>';
try { document.getElementById('kpi-daily-ton').closest('.metric').querySelector('.metric-sub').textContent = 'July 26, 2026 · all clients'; } catch(e){}
document.getElementById('kpi-month-ton').innerHTML = monthlyTotal.toLocaleString('en-IN', { maximumFractionDigits: 2 }) + ' <span style="font-size:0.9rem;font-weight:600">kg</span>';
try { document.getElementById('kpi-month-ton').closest('.metric').querySelector('.metric-sub').textContent = 'July 2026 cumulative'; } catch(e){}
document.getElementById('kpi-daily-avg').innerHTML =
  dailyAverage.toLocaleString('en-IN', { maximumFractionDigits: 0 }) +
  ' <span style="font-size:0.9rem;font-weight:600">kg/day</span>';

// ─── OPEN SHIPMENTS TABLE (Panel 1) ───────────────────────────────────────────
const openTableBody = document.getElementById('open-table-body');
if (openTableBody) {
  openTableBody.innerHTML = '';
  openData.forEach((d, i) => {
    const eddCount = (eddData.find(e => e.name === d.name) || {}).count || 0;
    const dueCount = (dueData.find(e => e.name === d.name) || {}).count || 0;
    const pctDelayed = Math.round(eddCount / d.count * 100);
    const risk = pctDelayed >= 70 ? ['Critical','delayed'] : pctDelayed >= 40 ? ['High','delayed'] : pctDelayed >= 20 ? ['Medium','open'] : ['Low','due'];
    openTableBody.innerHTML += `<tr>
      <td style="color:#94a3b8;font-size:0.8rem">${i+1}</td>
      <td><strong>${d.name}</strong></td>
      <td>${d.count}</td>
      <td style="color:#dc2626;font-weight:600">${eddCount}</td>
      <td style="color:#d97706;font-weight:600">${dueCount}</td>
      <td style="color:${pctDelayed>=50?'#dc2626':'#d97706'};font-weight:700">${pctDelayed}%</td>
      <td><span class="badge ${risk[1]}">${risk[0]}</span></td>
    </tr>`;
  });
}

// ─── CHART 1: Status Donut ─────────────────────────────────────────────────────
new Chart(document.getElementById('statusDonut'), {
  type: 'doughnut',
  data: {
    labels: ['EDD Crossed (Delayed)', 'Open (in transit)', 'Due Tomorrow', 'Booked Yesterday'],
    datasets: [{
      data: [eddTotal, openTotal - eddTotal, dueTotal, bookedTotal],
      backgroundColor: ['#ef4444', '#3b82f6', '#f59e0b', '#10b981'],
      borderWidth: 2, borderColor: '#ffffff', hoverOffset: 6
    }]
  },
  options: {
    responsive: true, maintainAspectRatio: false, cutout: '68%',
    plugins: {
      legend: { display: false },
      tooltip: { callbacks: { label: ctx => ` ${ctx.label}: ${ctx.parsed}` } }
    }
  }
});

// ─── CHART 2: EDD Crossed by Customer ────────────────────────────────────────
new Chart(document.getElementById('eddBarChart'), {
  type: 'bar',
  data: {
    labels: eddData.map(d => d.name),
    datasets: [{
      label: 'EDD Crossed',
      data: eddData.map(d => d.count),
      backgroundColor: 'rgba(239,68,68,0.12)',
      borderColor: '#ef4444',
      borderWidth: 1.5, borderRadius: 4
    }]
  },
  options: {
    indexAxis: 'y', responsive: true, maintainAspectRatio: false,
    plugins: { legend: { display: false } },
    scales: {
      x: { beginAtZero: true, ticks: { font: { size: 11 } } },
      y: { ticks: { font: { size: 11, weight: '500' } }, grid: { display: false } }
    }
  }
});

// ─── CHART 3: Due Tomorrow (July 28) ──────────────────────────────────────────
new Chart(document.getElementById('dueTmrChart'), {
  type: 'bar',
  data: {
    labels: dueData.map(d => d.name),
    datasets: [{
      label: 'Due Tomorrow',
      data: dueData.map(d => d.count),
      backgroundColor: 'rgba(245,158,11,0.12)',
      borderColor: '#f59e0b',
      borderWidth: 1.5, borderRadius: 4
    }]
  },
  options: {
    responsive: true, maintainAspectRatio: false,
    plugins: { legend: { display: false } },
    scales: {
      x: { ticks: { autoSkip: false, maxRotation: 30, font: { size: 11, weight: '500' } }, grid: { display: false } },
      y: { beginAtZero: true }
    }
  }
});

// ─── CHART 4: Booked Yesterday (July 26) ──────────────────────────────────────
new Chart(document.getElementById('bookedChart'), {
  type: 'bar',
  data: {
    labels: bookedData.map(d => d.name),
    datasets: [{
      label: 'Booked Yesterday',
      data: bookedData.map(d => d.count),
      backgroundColor: 'rgba(16,185,129,0.12)',
      borderColor: '#10b981',
      borderWidth: 1.5, borderRadius: 4
    }]
  },
  options: {
    responsive: true, maintainAspectRatio: false,
    plugins: { legend: { display: false } },
    scales: {
      x: { ticks: { autoSkip: false, maxRotation: 30, font: { size: 11, weight: '500' } }, grid: { display: false } },
      y: { beginAtZero: true }
    }
  }
});

// ─── PANEL 2: Tonnage — showing achieved vs target ────────────────────────────
// Completion color scale: red (low %) → green (near/at target) → blue (100%+)
function bucketColor(pct) {
  if (pct === null) return '#94a3b8';
  if (pct >= 100) return '#004df5';
  if (pct >= 90) return '#059669';
  if (pct >= 80) return '#10b981';
  if (pct >= 70) return '#34d399';
  if (pct >= 60) return '#84cc16';
  if (pct >= 50) return '#a3e635';
  if (pct >= 40) return '#eab308';
  if (pct >= 30) return '#f59e0b';
  if (pct >= 20) return '#fb923c';
  if (pct >= 10) return '#f87171';
  return '#ef4444';
}

function fmtKg(v) { return v.toLocaleString('en-IN', { maximumFractionDigits: 0 }); }

// Per-kg average rate (₹/kg), from the customer rate reference sheet (image, July 2026).
// Customers not listed there default to a flat ₹10/kg so every row still gets a value figure.
const RATE_PER_KG = {
  'Bombax':                          14.38,
  'Carrier Refrigeration':           11.26,
  'Carrier CTD':                     13.43,
  'Cosmos Pumps Pvt Ltd':            13.16,
  'Edusoft Healthcare Ltd':          13.77,
  'Frick India':                     33.52,
  'Haier CCR':                       16.53,
  'Kumar Services':                  10.20,
  'Loom Solar Pvt Ltd':              20.75,
  'Medical Science':                 11.64,
  'Mitras Technocrafts Pvt Ltd':     11.11,
  'Oneiric Appliances Pvt Ltd':      13.13,
  'SCJ COLOURS NEW':                 8.00,
  'Sukuga Technologies Pvt Ltd':     14.79,
  'Vaidrishi Laboratories Pvt Ltd':  12.73,
};
const DEFAULT_RATE_PER_KG = 10; // fallback for any customer not in the rate sheet
function rateFor(name) { return RATE_PER_KG[name] !== undefined ? RATE_PER_KG[name] : DEFAULT_RATE_PER_KG; }
function fmtRs(v) { return '₹' + v.toLocaleString('en-IN', { maximumFractionDigits: 0 }); }

const PERIOD_LABELS = {
  full:    'Tonnage achieved vs monthly target — % completion',
  first10: 'First 10 Days — tonnage achieved vs period target',
  mid10:   'Mid 10 Days — tonnage achieved vs period target',
  last10:  'Last 10 Days — tonnage achieved vs period target',
};
const PERIOD_SHORT_LABELS = {
  full: 'Full Month (Till Date)', first10: 'First 10 Days', mid10: 'Mid 10 Days', last10: 'Last 10 Days',
};

let currentPeriod = 'full';

// Pulls the achieved/target pair for a client for whichever period is selected — this single
// filter now drives the client bar list, both charts, and the KAM summary table below.
function getPeriodStats(c, period) {
  if (period === 'full') return { achieved: c.achieved, target: c.target };
  const p = c.periods && c.periods[period];
  return { achieved: p ? p.achieved : null, target: p ? p.target : null };
}

function setTonnagePeriod(period) {
  currentPeriod = period;
  renderTonnageBars();
  renderTonnageCharts();
  renderKamSummary();
}
window.setTonnagePeriod = setTonnagePeriod;

function renderTonnageBars() {
  const barsEl = document.getElementById('tonnage-bars');
  if (!barsEl) return;

  const titleEl = document.getElementById('tonnage-panel-title');
  if (titleEl) titleEl.textContent = PERIOD_LABELS[currentPeriod];

  const withData = clients.map(c => {
    const { achieved, target } = getPeriodStats(c, currentPeriod);
    return { c, achieved, target };
  }).filter(r =>
    (r.achieved !== null && r.achieved !== undefined && r.achieved > 0) ||
    (r.target !== null && r.target !== undefined && r.target > 0)
  );

  withData.sort((a, b) => (b.achieved || b.target || 0) - (a.achieved || a.target || 0));

  if (withData.length === 0) {
    barsEl.innerHTML = `<div class="tonnage-empty">No client data available for the selected period.</div>`;
    return;
  }

  barsEl.innerHTML = withData.map(({ c, achieved, target }) => {
    const hasTarget = target !== null && target !== undefined && target > 0;
    const hasAchieved = achieved !== null && achieved !== undefined && achieved > 0;
    const pct = (hasTarget && hasAchieved) ? Math.round(achieved / target * 100) : null;
    const displayPct = pct !== null ? Math.min(pct, 100) : (hasTarget && !hasAchieved ? 100 : null);
    const barWidth = displayPct !== null ? displayPct + '%' : '100%';
    const barColor = (hasTarget && !hasAchieved) ? '#cbd5e1' : bucketColor(pct);
    const pctLabel = pct !== null ? pct + '%' : '—';
    const newTag = c.isNew ? '<span class="new-tag">New</span>' : '';

    let targetAchieved;
    if (hasTarget && hasAchieved) {
      targetAchieved = `${fmtKg(achieved)} / ${fmtKg(target)} <span style="color:#94a3b8;font-weight:500">kg</span>`;
    } else if (hasTarget && !hasAchieved) {
      targetAchieved = `— / ${fmtKg(target)} <span style="color:#94a3b8;font-weight:500">kg</span> <span style="color:#cbd5e1;font-size:0.65rem">(achieved pending)</span>`;
    } else {
      targetAchieved = `${fmtKg(achieved)} <span style="color:#94a3b8;font-weight:500">kg</span>${currentPeriod !== 'full' ? ' <span style="color:#cbd5e1;font-size:0.65rem">(target pending)</span>' : ''}`;
    }

    // Estimated value = achieved kg × per-kg rate (rate sheet if listed, else default ₹10/kg)
    const rate = rateFor(c.name);
    const valueLine = hasAchieved
      ? `<div style="font-size:0.65rem;color:#94a3b8;margin-top:2px">${fmtRs(achieved * rate)} <span style="color:#cbd5e1">@₹${rate}/kg</span></div>`
      : '';

    return `<div class="client-row">
      <div class="client-name" title="${c.name}"><span class="client-name-text">${c.name}</span>${newTag}</div>
      <div class="client-person">${c.person}</div>
      <div class="prog-bar-wrap">
        <div class="prog-bar" style="width:${barWidth};background:${barColor}"></div>
      </div>
      <div class="pct-text" style="color:${barColor};font-size:0.75rem">${pctLabel}</div>
      <div class="client-tonnage">${targetAchieved}${valueLine}</div>
    </div>`;
  }).join('');
}
window.renderTonnageBars = renderTonnageBars;

// Legend for the completion colour scale
const tonnageLegendEl = document.getElementById('tonnage-legend');
if (tonnageLegendEl) {
  tonnageLegendEl.innerHTML = [
    ['0–40%', '#f59e0b'],
    ['40–70%', '#a3e635'],
    ['70–100%', '#10b981'],
    ['100%+', '#004df5'],
  ].map(([label, color]) => `<span><span class="legend-dot" style="background:${color}"></span>${label}</span>`).join('')
   + `<span><span class="new-tag" style="margin-left:0">New</span> recently onboarded client</span>`;
}

const chartFont = { size: 11, weight: '500' };

// Top clients for the "Monthly target distribution" chart (by achieved, falling back to target)
function getTopForPeriod(period, n) {
  const rows = clients.map(c => {
    const { achieved, target } = getPeriodStats(c, period);
    return { name: c.name, achieved: achieved || 0, target: target || 0 };
  }).filter(r => r.achieved > 0 || r.target > 0);
  rows.sort((a, b) => (b.achieved || b.target) - (a.achieved || a.target));
  return rows.slice(0, n);
}

// Top clients by % completion (achieved ÷ target) for the selected period — used by the
// "Achieved vs target comparison" chart, so it ranks by who's closest to/over target rather
// than by raw tonnage. Requires both a target and some achieved tonnage to be rankable, and
// re-computes automatically whenever the period filter changes.
function getTopByCompletion(period, n) {
  const rows = clients.map(c => {
    const { achieved, target } = getPeriodStats(c, period);
    return { name: c.name, achieved: achieved || 0, target: target || 0 };
  }).filter(r => r.target > 0 && r.achieved > 0);
  rows.forEach(r => { r.pct = r.achieved / r.target * 100; });
  rows.sort((a, b) => b.pct - a.pct);
  return rows.slice(0, n);
}

let targetChartInstance = null;
let achChartInstance = null;

function renderTonnageCharts() {
  const top8 = getTopForPeriod(currentPeriod, 8);
  const labels = top8.map(r => r.name);
  const periodShort = PERIOD_SHORT_LABELS[currentPeriod];

  if (targetChartInstance) targetChartInstance.destroy();
  targetChartInstance = new Chart(document.getElementById('targetChart'), {
    type: 'bar',
    data: {
      labels,
      datasets: [
        { label: 'Target (kg)', data: top8.map(r => r.target), backgroundColor: 'rgba(0,77,245,0.10)', borderColor: '#004df5', borderWidth: 1.5, borderRadius: 4 },
        { label: 'Achieved (kg)', data: top8.map(r => r.achieved), backgroundColor: 'rgba(16,185,129,0.20)', borderColor: '#10b981', borderWidth: 1.5, borderRadius: 4 }
      ]
    },
    options: {
      indexAxis: 'y', responsive: true, maintainAspectRatio: false,
      plugins: {
        legend: { position: 'bottom', labels: { boxWidth: 12, padding: 16, font: chartFont } },
        title: { display: true, text: `Target vs Achieved — ${periodShort}`, font: { size: 11 }, color: '#94a3b8' }
      },
      scales: {
        x: { beginAtZero: true, ticks: { callback: v => (v/1000).toFixed(0)+'k', font: chartFont } },
        y: { ticks: { font: chartFont }, grid: { display: false } }
      }
    }
  });

  // "Achieved vs target comparison" — top 8 ranked by % completion, not raw tonnage
  const topByPct = getTopByCompletion(currentPeriod, 8);
  const pctLabels = topByPct.map(r => r.name);

  if (achChartInstance) achChartInstance.destroy();
  if (topByPct.length === 0) {
    const el = document.getElementById('achChart');
    if (el) { el.getContext('2d').clearRect(0, 0, el.width, el.height); }
  } else {
    achChartInstance = new Chart(document.getElementById('achChart'), {
      type: 'bar',
      data: {
        labels: pctLabels,
        datasets: [
          { label: 'Target (kg)', data: topByPct.map(r => r.target), backgroundColor: 'rgba(0,77,245,0.10)', borderColor: '#004df5', borderWidth: 1.5, borderRadius: 4 },
          { label: 'Achieved (kg)', data: topByPct.map(r => r.achieved), backgroundColor: 'rgba(16,185,129,0.20)', borderColor: '#10b981', borderWidth: 1.5, borderRadius: 4 }
        ]
      },
      options: {
        indexAxis: 'y', responsive: true, maintainAspectRatio: false,
        plugins: {
          legend: { position: 'bottom', labels: { boxWidth: 12, padding: 16, font: chartFont } },
          title: { display: true, text: `Top 8 by % completion — ${periodShort}`, font: { size: 11 }, color: '#94a3b8' },
          tooltip: {
            callbacks: {
              afterBody: ctx => {
                const r = topByPct[ctx[0].dataIndex];
                return r ? `${Math.round(r.pct)}% of target` : '';
              }
            }
          }
        },
        scales: {
          x: { beginAtZero: true, ticks: { callback: v => (v/1000).toFixed(0)+'k', font: chartFont } },
          y: { ticks: { font: chartFont }, grid: { display: false } }
        }
      }
    });
  }
}
window.renderTonnageCharts = renderTonnageCharts;

// ─── PANEL 3: Daily Average Table ─────────────────────────────────────────────
const tbody = document.getElementById('daily-table-body');
if (tbody) {
  clients.filter(c => c.achieved > 0).forEach(c => {
    const pct      = c.target > 0 ? Math.round(c.achieved / c.target * 100) + '%' : '—';
    const pctColor = c.target > 0 ? (c.achieved >= c.target ? '#10b981' : '#004df5') : '#94a3b8';
    const remaining = c.target > 0 ? Math.max(c.target - c.achieved, 0).toLocaleString('en-IN') : '—';
    const daysToFinish = c.target > 0 && c.avgDay > 0 && c.remaining > 0
      ? parseFloat((c.remaining / c.avgDay).toFixed(1))
      : (c.target > 0 && c.remaining === 0 ? '✓' : '—');
    const targetDisplay = c.target > 0 ? c.target.toLocaleString('en-IN') : '—';
    tbody.innerHTML += `<tr>
      <td style="font-weight:600">${c.name}</td>
      <td style="font-size:0.8rem;color:#64748b">${c.person}</td>
      <td>${targetDisplay}</td>
      <td>${c.achieved.toLocaleString('en-IN')}</td>
      <td style="color:${pctColor};font-weight:700">${pct}</td>
      <td>${c.activeDays}</td>
      <td>${c.avgDay.toLocaleString('en-IN')}</td>
      <td style="color:#f59e0b">${remaining}</td>
      <td style="color:#ef4444">${daysToFinish}</td>
    </tr>`;
  });
}

// ─── CHART 7: Avg kg/day ──────────────────────────────────────────────────────
const topAvg = clients.filter(c => c.avgDay > 0).sort((a, b) => b.avgDay - a.avgDay).slice(0, 10);
new Chart(document.getElementById('avgDayChart'), {
  type: 'bar',
  data: {
    labels: topAvg.map(c => c.name),
    datasets: [{ label: 'Avg kg/day', data: topAvg.map(c => c.avgDay), backgroundColor: 'rgba(99,102,241,0.12)', borderColor: '#6366f1', borderWidth: 1.5, borderRadius: 4 }]
  },
  options: {
    indexAxis: 'y', responsive: true, maintainAspectRatio: false,
    plugins: { legend: { display: false } },
    scales: {
      x: { beginAtZero: true, ticks: { callback: v => v.toLocaleString('en-IN'), font: chartFont } },
      y: { ticks: { font: chartFont }, grid: { display: false } }
    }
  }
});

// ─── CHART 8: Days to Complete ────────────────────────────────────────────────
const daysChartEl = document.getElementById('daysChart');
if (daysChartEl) {
  const daysData = clients.filter(c => c.target > 0 && c.avgDay > 0 && c.remaining > 0)
    .sort((a, b) => b.daysNeeded - a.daysNeeded).slice(0, 10);
  new Chart(daysChartEl, {
    type: 'bar',
    data: {
      labels: daysData.map(c => c.name),
      datasets: [{
        label: 'Days to finish remaining target',
        data: daysData.map(c => c.daysNeeded),
        backgroundColor: daysData.map(c => c.daysNeeded > 18 ? 'rgba(239,68,68,0.18)' : 'rgba(245,158,11,0.18)'),
        borderColor: daysData.map(c => c.daysNeeded > 18 ? '#ef4444' : '#f59e0b'),
        borderWidth: 1.5, borderRadius: 4
      }]
    },
    options: {
      indexAxis: 'y', responsive: true, maintainAspectRatio: false,
      plugins: {
        legend: { display: false },
        title: { display: true, text: 'Estimated days to finish at current avg rate', font: { size: 11 }, color: '#94a3b8' }
      },
      scales: {
        x: { beginAtZero: true, ticks: { font: chartFont } },
        y: { ticks: { font: chartFont }, grid: { display: false } }
      }
    }
  });
}

// ─── PANEL 4: KAM-wise breakdown — merged into the Tonnage panel, period-aware ────
// Shows KAM name + total target + total achieved + % done for whichever period is selected.
// Clients with no target/achieved for a period contribute 0 to that period's KAM totals.
function renderKamSummary() {
  const body = document.getElementById('kam-summary-body');
  if (!body) return;

  const kamMap = {};
  clients.forEach(c => {
    const { achieved, target } = getPeriodStats(c, currentPeriod);
    if (!achieved && !target) return;
    if (!kamMap[c.person]) kamMap[c.person] = { person: c.person, totalTarget: 0, totalAchieved: 0 };
    kamMap[c.person].totalTarget += (target || 0);
    kamMap[c.person].totalAchieved += (achieved || 0);
  });
  const kamList = Object.values(kamMap).sort((a, b) => b.totalAchieved - a.totalAchieved);

  if (kamList.length === 0) {
    body.innerHTML = `<tr><td colspan="4" style="text-align:center;color:#94a3b8;padding:20px">No KAM data available for the selected period.</td></tr>`;
    return;
  }

  body.innerHTML = kamList.map(k => {
    const pct = k.totalTarget > 0 ? Math.round(k.totalAchieved / k.totalTarget * 100) : null;
    const pctColor = pct === null ? '#94a3b8' : bucketColor(pct);
    return `<tr>
      <td style="font-weight:700">${k.person}</td>
      <td>${k.totalTarget > 0 ? fmtKg(k.totalTarget) : '—'}</td>
      <td>${fmtKg(k.totalAchieved)}</td>
      <td style="color:${pctColor};font-weight:700">${pct !== null ? pct + '%' : '—'}</td>
    </tr>`;
  }).join('');
}
window.renderKamSummary = renderKamSummary;

// Initial render for the whole period-driven Tonnage panel
renderTonnageBars();
renderTonnageCharts();
renderKamSummary();
