Chart.defaults.color = '#475569';
Chart.defaults.font.family = 'Inter, system-ui, -apple-system, sans-serif';
Chart.defaults.font.size = 12;
Chart.defaults.plugins.tooltip.backgroundColor = '#0f172a';
Chart.defaults.plugins.tooltip.borderColor = '#1e293b';
Chart.defaults.plugins.tooltip.borderWidth = 1;
Chart.defaults.plugins.tooltip.titleFont = { weight: '600', size: 13 };
Chart.defaults.plugins.tooltip.bodyFont = { size: 12 };
Chart.defaults.plugins.tooltip.padding = 10;
Chart.defaults.scale.grid.color = '#e2e8f0';
Chart.defaults.scale.ticks.color = '#475569';

function switchTab(id, btn) {
  document.querySelectorAll('.tab').forEach(t => {
    t.classList.remove('active');
    t.setAttribute('aria-selected', 'false');
  });
  document.querySelectorAll('.panel').forEach(p => p.classList.remove('active'));
  document.getElementById('tab-' + id).classList.add('active');
  btn.classList.add('active');
  btn.setAttribute('aria-selected', 'true');
}
window.switchTab = switchTab;

// ─── AUTO-GENERATED FROM: MVLOAD_13_07_2026.xlsx ───────────────────────────
// Report Date : July 13, 2026 (last fully-closed day of data)
// Generated by MVIKAS Dashboard Processor

// NOTE: Monthly targets loaded from Tonnage_of_June_Month sheet (contains July 2026 target columns)
// Achieved = tonnage dispatched so far this month, from Total_Tonnage_this_month sheet (July 2026)
// KTB and MV-Zenotel are new customers appearing for the first time in this file (not green-highlighted,
// so not tagged "New" — that tag is reserved for the sheet's own new-customer highlighting convention).

const clients = [
  { name: 'Carrier Refrigeration',           person: 'Sangeet Dhasmana',  target: 293072.82, achieved: 73883.0,  activeDays: 13 },
  { name: 'Bombax',                          person: 'Sangeet Dhasmana',  target: 97357.44,  achieved: 43906.25, activeDays: 13 },
  { name: 'Carrier CTD',                     person: 'Deepak Sharma',     target: 29784.07,  achieved: 32520.18, activeDays: 13 },
  { name: 'Haier CCR',                       person: 'Deepak Sharma',     target: 0,         achieved: 1973.21,  activeDays: 13 },
  { name: 'Loom Solar Pvt Ltd',              person: 'Deepak Sharma',     target: 14457.83,  achieved: 900.0,    activeDays: 13 },
  { name: 'Kumar Services',                  person: 'Deepak Sharma',     target: 13725.49,  achieved: 4115.05,  activeDays: 13 },
  { name: 'Sukuga Technologies Pvt Ltd',     person: 'Deepak Sharma',     target: 10141.99,  achieved: 5289.37,  activeDays: 13 },
  { name: 'Cosmos Pumps Pvt Ltd',            person: 'Deepak Sharma',     target: 11398.18,  achieved: 4859.9,   activeDays: 13 },
  { name: 'Oneiric Appliances Pvt Ltd',      person: 'Deepak Sharma',     target: 15232.29,  achieved: 5429.2,   activeDays: 13 },
  { name: 'Paramount Surgimed Ltd',          person: 'Deepak Sharma',     target: 12038.52,  achieved: 0,        activeDays: 13 },
  { name: 'Medical Science',                 person: 'Sangeet Dhasmana',  target: 6013.75,   achieved: 0,        activeDays: 13 },
  { name: 'Mitras Technocrafts Pvt Ltd',     person: 'Deepak Sharma',     target: 13501.35,  achieved: 1220.01,  activeDays: 13 },
  { name: 'Vaidrishi Laboratories Pvt Ltd',  person: 'Sangeet Dhasmana',  target: 0,         achieved: 887.55,   activeDays: 13 },
  { name: 'Frick India',                     person: 'Deepak Sharma',     target: 0,         achieved: 0,        activeDays: 13 },
  { name: 'Indu Sports',                     person: 'Sangeet Dhasmana',  target: 0,         achieved: 0,        activeDays: 13 },
  { name: 'Stockarea',                       person: 'Deepak Sharma',     target: 0,         achieved: 0,        activeDays: 13 },
  { name: 'Global Impex',                    person: 'Anjali',            target: 0,         achieved: 0,        activeDays: 13 },
  { name: 'Edusoft Healthcare Ltd',          person: 'Deepak Sharma',     target: 3631.08,   achieved: 0,        activeDays: 13 },
  { name: 'Grover Innovations LLP',          person: 'Shiva',             target: 0,         achieved: 0,        activeDays: 13 },
  { name: 'GCPA',                            person: 'Shiva',             target: 0,         achieved: 0,        activeDays: 13 },
  { name: 'Pangea',                          person: 'Deepak Sharma',     target: 9090.91,   achieved: 0,        activeDays: 13 },
  { name: 'RSR',                             person: 'Deepak Sharma',     target: 5000,      achieved: 0,        activeDays: 13, isNew: true },
  { name: 'Epson',                           person: 'Sangeet Dhasmana',  target: 10000,     achieved: 1973.83,  activeDays: 13, isNew: true },
  { name: 'KRF',                             person: 'Not Alloted',       target: 0,         achieved: 0,        activeDays: 13, isNew: true },
  { name: 'Conficore',                       person: 'Sangeet Dhasmana',  target: 5000,      achieved: 445.0,    activeDays: 13, isNew: true },
  { name: 'KTB',                             person: 'Not Alloted',       target: 0,         achieved: 1014.03,  activeDays: 13 },
  { name: 'MV-Zenotel',                      person: 'Not Alloted',       target: 0,         achieved: 80.0,     activeDays: 13 },
];

clients.forEach(c => {
  c.pct = c.target > 0 ? Math.round(c.achieved / c.target * 100) : (c.achieved > 0 ? 999 : 0);
  c.avgDay = c.activeDays > 0 ? Math.round(c.achieved / c.activeDays) : 0;
  c.remaining = Math.max((c.target || 0) - c.achieved, 0);
  c.daysNeeded = c.avgDay > 0 && c.remaining > 0 ? parseFloat((c.remaining / c.avgDay).toFixed(1)) : (c.remaining === 0 ? 0 : 999);
});

// ─── 10-DAY PERIOD BREAKDOWN (First 10 / Mid 10 / Last 10 days) ───────────────
// Target tonnage per period, read directly from the sheet's own
// "First/Mid/Last 10 days Target (kg)" columns (MVLOAD_13_07_2026.xlsx).
const periodTarget = {
  'Carrier Refrigeration':           { first10: 92317.94, mid10: 87921.85, last10: 114298.4 },
  'Carrier CTD':                     { first10: 11466.87, mid10: 10126.58, last10: 8339.538 },
  'Mitras Technocrafts Pvt Ltd':     { first10: 4117.912, mid10: 4927.993, last10: 4387.939 },
  'Paramount Surgimed Ltd':          { first10: 1083.467, mid10: 2166.934, last10: 8788.122 },
  'Haier CCR':                       { first10: null, mid10: null, last10: null },
  'Bombax':                          { first10: 30180.81, mid10: 37482.61, last10: 29207.23 },
  'Global Impex':                    { first10: null, mid10: null, last10: null },
  'Kumar Services':                  { first10: 4598.039, mid10: 5421.569, last10: 3637.255 },
  'Edusoft Healthcare Ltd':          { first10: 2904.866, mid10: 726.2164, last10: 0.0 },
  'Oneiric Appliances Pvt Ltd':      { first10: 6626.047, mid10: 4112.719, last10: 4493.526 },
  'Vaidrishi Laboratories Pvt Ltd':  { first10: null, mid10: null, last10: null },
  'Sukuga Technologies Pvt Ltd':     { first10: 1470.588, mid10: 4665.314, last10: 4006.085 },
  'Cosmos Pumps Pvt Ltd':            { first10: 3647.416, mid10: 4331.307, last10: 3362.462 },
  'Loom Solar Pvt Ltd':              { first10: 4192.771, mid10: 4481.928, last10: 5783.133 },
  'GCPA':                            { first10: null, mid10: null, last10: null },
  'Pangea':                          { first10: 3030.303, mid10: 3030.303, last10: 3030.303 },
  'RSR':                             { first10: 1666.667, mid10: 1666.667, last10: 1666.667 },
  'Medical Science':                 { first10: 0.0, mid10: 1924.399, last10: 4089.347 },
  'Epson':                           { first10: 3333.333, mid10: 3333.333, last10: 3333.333 },
  'KRF':                             { first10: null, mid10: null, last10: null },
  'Frick India':                     { first10: null, mid10: null, last10: null },
  'Indu Sports':                     { first10: null, mid10: null, last10: null },
  'Conficore':                       { first10: 1666.667, mid10: 1666.667, last10: 1666.667 },
  'KTB':                             { first10: null, mid10: null, last10: null },
  'MV-Zenotel':                      { first10: null, mid10: null, last10: null },
};

// Achieved tonnage per period — day-wise figures from the Tonnage_of_June_Month sheet
// (MVLOAD_13_07_2026.xlsx), summed for days 1-10, 11-20, and 21-30 per customer.
// As of this file, July 1-13 has closed data — First 10 Days is now complete, Mid 10 Days
// has partial achieved (days 11-13), and Last 10 Days is still fully pending (null).
const periodAchieved = {
  'Carrier Refrigeration':           { first10: 55456.0, mid10: 18427.0, last10: null },
  'Carrier CTD':                     { first10: 26996.05, mid10: 6111.1, last10: null },
  'Mitras Technocrafts Pvt Ltd':     { first10: 935.01, mid10: 285.0, last10: null },
  'Paramount Surgimed Ltd':          { first10: null, mid10: null, last10: null },
  'Haier CCR':                       { first10: 1973.15, mid10: null, last10: null },
  'Bombax':                          { first10: 37481.48, mid10: 8875.3, last10: null },
  'Global Impex':                    { first10: null, mid10: null, last10: null },
  'Kumar Services':                  { first10: 4114.98, mid10: null, last10: null },
  'Edusoft Healthcare Ltd':          { first10: null, mid10: null, last10: null },
  'Oneiric Appliances Pvt Ltd':      { first10: 5429.2, mid10: null, last10: null },
  'Vaidrishi Laboratories Pvt Ltd':  { first10: 750.0, mid10: 137.55, last10: null },
  'Sukuga Technologies Pvt Ltd':     { first10: 4604.3, mid10: 685.0, last10: null },
  'Cosmos Pumps Pvt Ltd':            { first10: 4249.9, mid10: 610.0, last10: null },
  'Loom Solar Pvt Ltd':              { first10: 900.0, mid10: null, last10: null },
  'GCPA':                            { first10: null, mid10: null, last10: null },
  'Pangea':                          { first10: null, mid10: null, last10: null },
  'RSR':                             { first10: null, mid10: null, last10: null },
  'Medical Science':                 { first10: null, mid10: null, last10: null },
  'Epson':                           { first10: 1653.8, mid10: 320.0, last10: null },
  'KRF':                             { first10: null, mid10: null, last10: null },
  'Frick India':                     { first10: null, mid10: null, last10: null },
  'Indu Sports':                     { first10: null, mid10: null, last10: null },
  'Conficore':                       { first10: 445.0, mid10: null, last10: null },
  'KTB':                             { first10: 930.02, mid10: 84.0, last10: null },
  'MV-Zenotel':                      { first10: 80.0, mid10: null, last10: null },
};

clients.forEach(c => {
  const t = periodTarget[c.name];
  const a = periodAchieved[c.name];
  c.periods = {
    first10: { target: t ? t.first10 : null, achieved: a ? a.first10 : null },
    mid10:   { target: t ? t.mid10   : null, achieved: a ? a.mid10   : null },
    last10:  { target: t ? t.last10  : null, achieved: a ? a.last10  : null },
  };
});

// Customer-level counts, matching the real 'Order EDD Crossed' sheet (164 orders, as of July 13, 2026)
// Note: this file's EDD Crossed sheet no longer includes a DelayReason column, so per-order reasons
// show as "Not specified" in the drill-down panel until that column reappears in a future file.
const eddData = [
  { name: 'Bombax',                 count: 60  },
  { name: 'Carrier Refrigeration',  count: 53  },
  { name: 'Carrier - CTD',          count: 9   },
  { name: 'KTB',                    count: 8   },
  { name: 'Haier CCR',              count: 7   },
  { name: 'Sukuga',                 count: 5   },
  { name: 'Stockarea',              count: 4   },
  { name: 'Epson India',            count: 4   },
  { name: 'MITRAS',                 count: 3   },
  { name: 'Kumar Services',         count: 3   },
  { name: 'MVIKAS Tech',            count: 2   },
  { name: 'Conficore',              count: 2   },
  { name: 'Paramount Surgimed Ltd', count: 1   },
  { name: 'Indu Sports',            count: 1   },
  { name: 'Oneric Appliances',      count: 1   },
  { name: 'Loom Solar',             count: 1   },
];
const eddTotal = eddData.reduce((a, b) => a + b.count, 0);

// ─── EDD CROSSED — per-order detail (drill-down panel) ────────────────────────
// Sourced from the 'Order EDD Crossed' sheet: Order_id, Customername, TransporterName, EDD, DelayReasons
const eddDetail = [
  { id:"MVS/26-27/1304", name:"Bombax", transporter:"EKART", edd:"28 Apr 2026", reason:null },
  { id:"MVS/26-27/2003", name:"Bombax", transporter:"EKART", edd:"08 May 2026", reason:null },
  { id:"MVS/26-27/2679", name:"Bombax", transporter:"EKART", edd:"17 May 2026", reason:null },
  { id:"MVS/26-27/2680", name:"Bombax", transporter:"EKART", edd:"19 May 2026", reason:null },
  { id:"MVS/26-27/2684", name:"Bombax", transporter:"EKART", edd:"17 May 2026", reason:null },
  { id:"MVS/26-27/2692", name:"Bombax", transporter:"EKART", edd:"19 May 2026", reason:null },
  { id:"MVS/26-27/2694", name:"Bombax", transporter:"EKART", edd:"19 May 2026", reason:null },
  { id:"MVS/26-27/2698", name:"Bombax", transporter:"EKART", edd:"19 May 2026", reason:null },
  { id:"MVS/26-27/2764", name:"Bombax", transporter:"EKART", edd:"20 May 2026", reason:null },
  { id:"MVS/26-27/2874", name:"Bombax", transporter:"EKART", edd:"24 May 2026", reason:null },
  { id:"MVS/26-27/2900", name:"Bombax", transporter:"EKART", edd:"22 May 2026", reason:null },
  { id:"MVS/26-27/3032", name:"Bombax", transporter:"EKART", edd:"23 May 2026", reason:null },
  { id:"MVS/26-27/4080", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"02 Jun 2026", reason:null },
  { id:"MVS/26-27/4353", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"05 Jun 2026", reason:null },
  { id:"MVS/26-27/4385", name:"Sukuga", transporter:"EKARTD", edd:"08 Jun 2026", reason:null },
  { id:"MVS/26-27/4843", name:"Stockarea", transporter:null, edd:"06 Jun 2026", reason:null },
  { id:"MVS/26-27/5313", name:"Bombax", transporter:"EKART", edd:"15 Jun 2026", reason:null },
  { id:"MVS/26-27/5340", name:"Carrier Refrigeration", transporter:"EKART", edd:"13 Jun 2026", reason:null },
  { id:"MVS/26-27/5362", name:"Carrier Refrigeration", transporter:"EKART", edd:"18 Jun 2026", reason:null },
  { id:"MVS/26-27/5438", name:"Carrier Refrigeration", transporter:"EKART", edd:"19 Jun 2026", reason:null },
  { id:"MVS/26-27/5489", name:"MVIKAS Tech", transporter:null, edd:"22 Jun 2026", reason:null },
  { id:"MVS/26-27/5569", name:"Carrier Refrigeration", transporter:"EKART", edd:"22 Jun 2026", reason:null },
  { id:"MVS/26-27/5676", name:"Stockarea", transporter:null, edd:"19 Jun 2026", reason:null },
  { id:"MVS/26-27/5677", name:"Stockarea", transporter:null, edd:"19 Jun 2026", reason:null },
  { id:"MVS/26-27/5678", name:"Stockarea", transporter:null, edd:"19 Jun 2026", reason:null },
  { id:"MVS/26-27/5859", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"26 Jun 2026", reason:null },
  { id:"MVS/26-27/5992", name:"Paramount Surgimed Ltd", transporter:"GATI", edd:"01 Jul 2026", reason:null },
  { id:"MVS/26-27/6257", name:"Indu Sports", transporter:"EKART", edd:"30 Jun 2026", reason:null },
  { id:"MVS/26-27/6258", name:"Carrier Refrigeration", transporter:"EKART", edd:"27 Jun 2026", reason:null },
  { id:"MVS/26-27/6259", name:"Bombax", transporter:"EKART", edd:"01 Jul 2026", reason:null },
  { id:"MVS/26-27/6260", name:"Bombax", transporter:"EKART", edd:"30 Jun 2026", reason:null },
  { id:"MVS/26-27/6261", name:"Bombax", transporter:"EKART", edd:"02 Jul 2026", reason:null },
  { id:"MVS/26-27/6262", name:"Bombax", transporter:"EKART", edd:"01 Jul 2026", reason:null },
  { id:"MVS/26-27/6263", name:"Bombax", transporter:"EKART", edd:"01 Jul 2026", reason:null },
  { id:"MVS/26-27/6264", name:"Bombax", transporter:"EKART", edd:"30 Jun 2026", reason:null },
  { id:"MVS/26-27/6265", name:"Bombax", transporter:"EKART", edd:"02 Jul 2026", reason:null },
  { id:"MVS/26-27/6266", name:"Bombax", transporter:"EKART", edd:"03 Jul 2026", reason:null },
  { id:"MVS/26-27/6267", name:"Bombax", transporter:"EKART", edd:"01 Jul 2026", reason:null },
  { id:"MVS/26-27/6268", name:"Bombax", transporter:"EKART", edd:"29 Jun 2026", reason:null },
  { id:"MVS/26-27/6269", name:"Bombax", transporter:"EKART", edd:"03 Jul 2026", reason:null },
  { id:"MVS/26-27/6270", name:"Bombax", transporter:"EKART", edd:"29 Jun 2026", reason:null },
  { id:"MVS/26-27/6271", name:"Bombax", transporter:"EKART", edd:"29 Jun 2026", reason:null },
  { id:"MVS/26-27/6272", name:"Bombax", transporter:"EKART", edd:"03 Jul 2026", reason:null },
  { id:"MVS/26-27/6273", name:"Bombax", transporter:"EKART", edd:"29 Jun 2026", reason:null },
  { id:"MVS/26-27/6274", name:"Haier CCR", transporter:"EKART", edd:"29 Jun 2026", reason:null },
  { id:"MVS/26-27/6275", name:"Haier CCR", transporter:"EKART", edd:"29 Jun 2026", reason:null },
  { id:"MVS/26-27/6276", name:"Haier CCR", transporter:"EKART", edd:"27 Jun 2026", reason:null },
  { id:"MVS/26-27/6277", name:"Haier CCR", transporter:"EKART", edd:"27 Jun 2026", reason:null },
  { id:"MVS/26-27/6278", name:"Haier CCR", transporter:"EKART", edd:"27 Jun 2026", reason:null },
  { id:"MVS/26-27/6279", name:"Haier CCR", transporter:"EKART", edd:"27 Jun 2026", reason:null },
  { id:"MVS/26-27/6291", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"30 Jun 2026", reason:null },
  { id:"MVS/26-27/6340", name:"Bombax", transporter:"EKART", edd:"29 Jun 2026", reason:null },
  { id:"MVS/26-27/6414", name:"Bombax", transporter:"EKART", edd:"03 Jul 2026", reason:null },
  { id:"MVS/26-27/6425", name:"Bombax", transporter:"EKART", edd:"30 Jun 2026", reason:null },
  { id:"MVS/26-27/6498", name:"Bombax", transporter:"XP INDIA", edd:"03 Jul 2026", reason:null },
  { id:"MVS/26-27/6589", name:"Bombax", transporter:"EKART", edd:"03 Jul 2026", reason:null },
  { id:"MVS/26-27/6627", name:"Bombax", transporter:"EKART", edd:"04 Jul 2026", reason:null },
  { id:"MVS/26-27/6654", name:"Bombax", transporter:"DP WORLD", edd:"09 Jul 2026", reason:null },
  { id:"MVS/26-27/6656", name:"Bombax", transporter:"DP WORLD", edd:"09 Jul 2026", reason:null },
  { id:"MVS/26-27/6662", name:"Carrier Refrigeration", transporter:"DP WORLD", edd:"07 Jul 2026", reason:null },
  { id:"MVS/26-27/6673", name:"Bombax", transporter:"EKART", edd:"06 Jul 2026", reason:null },
  { id:"MVS/26-27/6674", name:"Bombax", transporter:"EKART", edd:"07 Jul 2026", reason:null },
  { id:"MVS/26-27/6675", name:"Bombax", transporter:"EKART", edd:"06 Jul 2026", reason:null },
  { id:"MVS/26-27/6765", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"05 Jul 2026", reason:null },
  { id:"MVS/26-27/6771", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"07 Jul 2026", reason:null },
  { id:"MVS/26-27/6774", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"05 Jul 2026", reason:null },
  { id:"MVS/26-27/6780", name:"MITRAS", transporter:"DELHIVERY", edd:"04 Jul 2026", reason:null },
  { id:"MVS/26-27/6806", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"06 Jul 2026", reason:null },
  { id:"MVS/26-27/6865", name:"Bombax", transporter:"DP WORLD", edd:"10 Jul 2026", reason:null },
  { id:"MVS/26-27/6908", name:"Sukuga", transporter:"GATI", edd:"09 Jul 2026", reason:null },
  { id:"MVS/26-27/6913", name:"MITRAS", transporter:"DELHIVERY", edd:"05 Jul 2026", reason:null },
  { id:"MVS/26-27/6945", name:"Carrier Refrigeration", transporter:"EKART", edd:"04 Jul 2026", reason:null },
  { id:"MVS/26-27/6947", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"06 Jul 2026", reason:null },
  { id:"MVS/26-27/6952", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"06 Jul 2026", reason:null },
  { id:"MVS/26-27/6953", name:"Oneric Appliances", transporter:"DELHIVERY", edd:"12 Jul 2026", reason:null },
  { id:"MVS/26-27/6960", name:"Bombax", transporter:"DP WORLD", edd:"09 Jul 2026", reason:null },
  { id:"MVS/26-27/7020", name:"Bombax", transporter:"EKART", edd:"10 Jul 2026", reason:null },
  { id:"MVS/26-27/7037", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"11 Jul 2026", reason:null },
  { id:"MVS/26-27/7042", name:"Bombax", transporter:"DP World", edd:"09 Jul 2026", reason:null },
  { id:"MVS/26-27/7098", name:"Bombax", transporter:"EKART", edd:"12 Jul 2026", reason:null },
  { id:"MVS/26-27/7103", name:"Bombax", transporter:"EKART", edd:"11 Jul 2026", reason:null },
  { id:"MVS/26-27/7106", name:"Bombax", transporter:"EKART", edd:"12 Jul 2026", reason:null },
  { id:"MVS/26-27/7116", name:"Sukuga", transporter:"LAST MILE", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7118", name:"Sukuga", transporter:"LAST MILE", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7119", name:"Sukuga", transporter:"LAST MILE", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7133", name:"Bombax", transporter:"DP World", edd:"12 Jul 2026", reason:null },
  { id:"MVS/26-27/7136", name:"Bombax", transporter:"DP World", edd:"10 Jul 2026", reason:null },
  { id:"MVS/26-27/7138", name:"Bombax", transporter:"DP World", edd:"10 Jul 2026", reason:null },
  { id:"MVS/26-27/7144", name:"Loom Solar", transporter:"XP INDIA", edd:"10 Jul 2026", reason:null },
  { id:"MVS/26-27/7146", name:"Bombax", transporter:"DP World", edd:"10 Jul 2026", reason:null },
  { id:"MVS/26-27/7152", name:"Bombax", transporter:"DP World", edd:"08 Jul 2026", reason:null },
  { id:"MVS/26-27/7167", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"12 Jul 2026", reason:null },
  { id:"MVS/26-27/7177", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"12 Jul 2026", reason:null },
  { id:"MVS/26-27/7184", name:"Kumar Services", transporter:"EKART", edd:"11 Jul 2026", reason:null },
  { id:"MVS/26-27/7198", name:"MVIKAS Tech", transporter:null, edd:"10 Jul 2026", reason:null },
  { id:"MVS/26-27/7206", name:"Carrier - CTD", transporter:"EKART", edd:"12 Jul 2026", reason:null },
  { id:"MVS/26-27/7207", name:"Carrier - CTD", transporter:"EKART", edd:"12 Jul 2026", reason:null },
  { id:"MVS/26-27/7220", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"12 Jul 2026", reason:null },
  { id:"MVS/26-27/7221", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7223", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7226", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"10 Jul 2026", reason:null },
  { id:"MVS/26-27/7233", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7237", name:"Carrier - CTD", transporter:"DP WORLD", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7239", name:"Carrier - CTD", transporter:"DP WORLD", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7241", name:"Epson India", transporter:"EKART", edd:"11 Jul 2026", reason:null },
  { id:"MVS/26-27/7263", name:"Bombax", transporter:"EKART", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7277", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7280", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"11 Jul 2026", reason:null },
  { id:"MVS/26-27/7283", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7286", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7289", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"12 Jul 2026", reason:null },
  { id:"MVS/26-27/7291", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7294", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7296", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7299", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7310", name:"Bombax", transporter:"DP WORLD", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7333", name:"Bombax", transporter:"DP WORLD", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7336", name:"Bombax", transporter:"DP WORLD", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7347", name:"KTB", transporter:null, edd:"10 Jul 2026", reason:null },
  { id:"MVS/26-27/7348", name:"Kumar Services", transporter:"LAST MILE", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7349", name:"Kumar Services", transporter:"LAST MILE", edd:"11 Jul 2026", reason:null },
  { id:"MVS/26-27/7350", name:"KTB", transporter:null, edd:"10 Jul 2026", reason:null },
  { id:"MVS/26-27/7352", name:"Epson India", transporter:"EKART", edd:"12 Jul 2026", reason:null },
  { id:"MVS/26-27/7356", name:"KTB", transporter:null, edd:"10 Jul 2026", reason:null },
  { id:"MVS/26-27/7357", name:"KTB", transporter:null, edd:"10 Jul 2026", reason:null },
  { id:"MVS/26-27/7358", name:"KTB", transporter:null, edd:"10 Jul 2026", reason:null },
  { id:"MVS/26-27/7359", name:"KTB", transporter:null, edd:"10 Jul 2026", reason:null },
  { id:"MVS/26-27/7363", name:"Carrier - CTD", transporter:"EKART", edd:"12 Jul 2026", reason:null },
  { id:"MVS/26-27/7373", name:"Bombax", transporter:"EKART", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7383", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"12 Jul 2026", reason:null },
  { id:"MVS/26-27/7384", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7414", name:"Carrier Refrigeration", transporter:"EKART", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7416", name:"Carrier Refrigeration", transporter:"EKART", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7419", name:"Carrier Refrigeration", transporter:"EKART", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7420", name:"Carrier Refrigeration", transporter:"EKART", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7424", name:"Carrier Refrigeration", transporter:"EKART", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7425", name:"Carrier Refrigeration", transporter:"EKART", edd:"11 Jul 2026", reason:null },
  { id:"MVS/26-27/7426", name:"Carrier Refrigeration", transporter:"EKART", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7427", name:"Carrier Refrigeration", transporter:"EKART", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7428", name:"Carrier Refrigeration", transporter:"EKART", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7431", name:"Carrier Refrigeration", transporter:"EKART", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7434", name:"Carrier Refrigeration", transporter:"EKART", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7437", name:"Carrier Refrigeration", transporter:"EKART", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7441", name:"Carrier Refrigeration", transporter:"EKART", edd:"12 Jul 2026", reason:null },
  { id:"MVS/26-27/7443", name:"Carrier Refrigeration", transporter:"EKART", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7448", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"11 Jul 2026", reason:null },
  { id:"MVS/26-27/7450", name:"Bombax", transporter:"DP WORLD", edd:"12 Jul 2026", reason:null },
  { id:"MVS/26-27/7460", name:"Bombax", transporter:"DP WORLD", edd:"11 Jul 2026", reason:null },
  { id:"MVS/26-27/7461", name:"Bombax", transporter:"DP WORLD", edd:"11 Jul 2026", reason:null },
  { id:"MVS/26-27/7510", name:"MITRAS", transporter:"EKART", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7512", name:"Conficore", transporter:"GATI", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7513", name:"Conficore", transporter:"GATI", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7523", name:"Carrier - CTD", transporter:"EKART", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7524", name:"Carrier - CTD", transporter:"EKART", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7544", name:"Carrier - CTD", transporter:"EKART", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7548", name:"Carrier - CTD", transporter:"EKART", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7550", name:"Epson India", transporter:"EKART", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7551", name:"Epson India", transporter:"EKART", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7569", name:"Haier CCR", transporter:"EKART", edd:"12 Jul 2026", reason:null },
  { id:"MVS/26-27/7594", name:"Carrier Refrigeration", transporter:"EKART", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7625", name:"Bombax", transporter:"DP WORLD", edd:"13 Jul 2026", reason:null },
  { id:"MVS/26-27/7646", name:"KTB", transporter:null, edd:"12 Jul 2026", reason:null },
  { id:"MVS/26-27/7647", name:"KTB", transporter:null, edd:"12 Jul 2026", reason:null },
  { id:"MVS/26-27/7736", name:"Carrier Refrigeration", transporter:"XP INDIA", edd:"13 Jul 2026", reason:null },
];

function renderEddDetail(filterText) {
  const tbody = document.getElementById('edd-detail-body');
  const countEl = document.getElementById('edd-detail-count');
  if (!tbody) return;
  const q = (filterText || '').trim().toLowerCase();
  const rows = q
    ? eddDetail.filter(r => r.name.toLowerCase().includes(q) || r.id.toLowerCase().includes(q) || (r.transporter || '').toLowerCase().includes(q))
    : eddDetail;

  if (countEl) countEl.textContent = `${rows.length} of ${eddDetail.length} orders`;

  if (rows.length === 0) {
    tbody.innerHTML = `<tr><td colspan="4" style="text-align:center;color:#94a3b8;padding:24px">No matching orders.</td></tr>`;
    return;
  }

  tbody.innerHTML = rows.map(r => `<tr>
      <td style="font-weight:600">${r.id}</td>
      <td>${r.name}</td>
      <td>${r.transporter || '—'}</td>
      <td style="color:#dc2626;font-weight:600">${r.edd || '—'}</td>
    </tr>`).join('');
}
window.renderEddDetail = renderEddDetail;

// Jump from the EDD Crossed KPI card straight to the drill-down panel
function goToEddDetail() {
  const btn = document.getElementById('tab-btn-edd');
  if (btn) switchTab('edd', btn);
  const panel = document.getElementById('tab-edd');
  if (panel) panel.scrollIntoView({ behavior: 'smooth', block: 'start' });
}
window.goToEddDetail = goToEddDetail;

const openData = [
  { name: 'Carrier Refrigeration',    count: 196 },
  { name: 'Bombax',                   count: 180 },
  { name: 'Carrier - CTD',            count: 69  },
  { name: 'Sukuga',                   count: 13  },
  { name: 'Epson India',              count: 10  },
  { name: 'KTB',                      count: 8   },
  { name: 'Cosmos Pumps Pvt. Ltd.',   count: 5   },
  { name: 'MITRAS',                   count: 4   },
  { name: 'Kumar Services',           count: 4   },
  { name: 'Paramount Surgimed Ltd',   count: 1   },
  { name: 'Oneric Appliances',        count: 1   },
  { name: 'Conficore',                count: 1   },
  { name: 'Haier CCR',                count: 1   },
  { name: 'Vaidrishi Laboratories',   count: 1   },
];
const openTotal = openData.reduce((a, b) => a + b.count, 0);

const dueData = [
  { name: 'Carrier Refrigeration',  count: 55 },
  { name: 'Bombax',                 count: 24 },
  { name: 'Carrier - CTD',          count: 15 },
  { name: 'Cosmos Pumps Pvt. Ltd.', count: 2  },
  { name: 'Sukuga',                 count: 1  },
  { name: 'Epson India',            count: 1  },
];
const dueTotal = dueData.reduce((a, b) => a + b.count, 0);

const bookedData = [
  { name: 'Carrier Refrigeration',  count: 63 },
  { name: 'Bombax',                 count: 37 },
  { name: 'Carrier - CTD',          count: 17 },
  { name: 'Sukuga',                 count: 3  },
  { name: 'Vaidrishi Laboratories', count: 1  },
  { name: 'MITRAS',                 count: 1  },
];
const bookedTotal = bookedData.reduce((a, b) => a + b.count, 0);

const dailyTonnageData = [
  { name: 'Carrier Refrigeration',  kg: 8361.00 },
  { name: 'Bombax',                 kg: 4058.38 },
  { name: 'Carrier - CTD',          kg: 667.10  },
  { name: 'Sukuga',                 kg: 685.07  },
  { name: 'MITRAS',                 kg: 285.00  },
];
const dailyTotal = dailyTonnageData.reduce((a, b) => a + b.kg, 0);

const monthlyTotal = clients.reduce((a, c) => a + c.achieved, 0);
const daysInMonth = 31; // July has 31 days
const activeDaysElapsed = 13; // through July 13, 2026 (last fully-closed day of data)
const dailyAverage = monthlyTotal / activeDaysElapsed; // avg over active days

// ─── UPDATE HEADER ─────────────────────────────────────────────────────────────
const elDate = document.querySelector('.badge-date');
const elElapsed = document.querySelector('.badge-elapsed');
if (elDate) elDate.textContent = 'As of July 13, 2026';
if (elElapsed) elElapsed.textContent = '13 / 31 days elapsed · July 2026';

// ─── UPDATE KPI CARDS ─────────────────────────────────────────────────────────
document.getElementById('kpi-open').textContent = openTotal;
document.getElementById('kpi-edd').textContent = eddTotal;
document.getElementById('kpi-edd-pct').textContent = Math.round(eddTotal / openTotal * 100) + '% of open';
renderEddDetail('');
document.getElementById('kpi-due').textContent = dueTotal;
document.getElementById('kpi-booked').textContent = bookedTotal;
try { document.getElementById('kpi-booked').closest('.metric').querySelector('.metric-sub').textContent = 'July 13, 2026'; } catch(e){}
document.getElementById('kpi-daily-ton').innerHTML = dailyTotal.toLocaleString('en-IN', { maximumFractionDigits: 2 }) + ' <span style="font-size:0.9rem;font-weight:600">kg</span>';
try { document.getElementById('kpi-daily-ton').closest('.metric').querySelector('.metric-sub').textContent = 'July 13, 2026 · all clients'; } catch(e){}
document.getElementById('kpi-month-ton').innerHTML = monthlyTotal.toLocaleString('en-IN', { maximumFractionDigits: 2 }) + ' <span style="font-size:0.9rem;font-weight:600">kg</span>';
try { document.getElementById('kpi-month-ton').closest('.metric').querySelector('.metric-sub').textContent = 'July 2026 cumulative'; } catch(e){}
document.getElementById('kpi-daily-avg').innerHTML =
  dailyAverage.toLocaleString('en-IN', { maximumFractionDigits: 0 }) +
  ' <span style="font-size:0.9rem;font-weight:600">kg/day</span>';

// ─── OPEN SHIPMENTS TABLE (Panel 1) ───────────────────────────────────────────
const openTableBody = document.getElementById('open-table-body');
if (openTableBody) {
  openTableBody.innerHTML = '';
  openData.forEach((d, i) => {
    const eddCount = (eddData.find(e => e.name === d.name) || {}).count || 0;
    const dueCount = (dueData.find(e => e.name === d.name) || {}).count || 0;
    const pctDelayed = Math.round(eddCount / d.count * 100);
    const risk = pctDelayed >= 70 ? ['Critical','delayed'] : pctDelayed >= 40 ? ['High','delayed'] : pctDelayed >= 20 ? ['Medium','open'] : ['Low','due'];
    openTableBody.innerHTML += `<tr>
      <td style="color:#94a3b8;font-size:0.8rem">${i+1}</td>
      <td><strong>${d.name}</strong></td>
      <td>${d.count}</td>
      <td style="color:#dc2626;font-weight:600">${eddCount}</td>
      <td style="color:#d97706;font-weight:600">${dueCount}</td>
      <td style="color:${pctDelayed>=50?'#dc2626':'#d97706'};font-weight:700">${pctDelayed}%</td>
      <td><span class="badge ${risk[1]}">${risk[0]}</span></td>
    </tr>`;
  });
}

// ─── CHART 1: Status Donut ─────────────────────────────────────────────────────
new Chart(document.getElementById('statusDonut'), {
  type: 'doughnut',
  data: {
    labels: ['EDD Crossed (Delayed)', 'Open (in transit)', 'Due Tomorrow', 'Booked Yesterday'],
    datasets: [{
      data: [eddTotal, openTotal - eddTotal, dueTotal, bookedTotal],
      backgroundColor: ['#ef4444', '#3b82f6', '#f59e0b', '#10b981'],
      borderWidth: 2, borderColor: '#ffffff', hoverOffset: 6
    }]
  },
  options: {
    responsive: true, maintainAspectRatio: false, cutout: '68%',
    plugins: {
      legend: { display: false },
      tooltip: { callbacks: { label: ctx => ` ${ctx.label}: ${ctx.parsed}` } }
    }
  }
});

// ─── CHART 2: EDD Crossed by Customer ────────────────────────────────────────
new Chart(document.getElementById('eddBarChart'), {
  type: 'bar',
  data: {
    labels: eddData.map(d => d.name),
    datasets: [{
      label: 'EDD Crossed',
      data: eddData.map(d => d.count),
      backgroundColor: 'rgba(239,68,68,0.12)',
      borderColor: '#ef4444',
      borderWidth: 1.5, borderRadius: 4
    }]
  },
  options: {
    indexAxis: 'y', responsive: true, maintainAspectRatio: false,
    plugins: { legend: { display: false } },
    scales: {
      x: { beginAtZero: true, ticks: { font: { size: 11 } } },
      y: { ticks: { font: { size: 11, weight: '500' } }, grid: { display: false } }
    }
  }
});

// ─── CHART 3: Due Tomorrow (July 15) ──────────────────────────────────────────
new Chart(document.getElementById('dueTmrChart'), {
  type: 'bar',
  data: {
    labels: dueData.map(d => d.name),
    datasets: [{
      label: 'Due Tomorrow',
      data: dueData.map(d => d.count),
      backgroundColor: 'rgba(245,158,11,0.12)',
      borderColor: '#f59e0b',
      borderWidth: 1.5, borderRadius: 4
    }]
  },
  options: {
    responsive: true, maintainAspectRatio: false,
    plugins: { legend: { display: false } },
    scales: {
      x: { ticks: { autoSkip: false, maxRotation: 30, font: { size: 11, weight: '500' } }, grid: { display: false } },
      y: { beginAtZero: true }
    }
  }
});

// ─── CHART 4: Booked Yesterday (July 13) ──────────────────────────────────────
new Chart(document.getElementById('bookedChart'), {
  type: 'bar',
  data: {
    labels: bookedData.map(d => d.name),
    datasets: [{
      label: 'Booked Yesterday',
      data: bookedData.map(d => d.count),
      backgroundColor: 'rgba(16,185,129,0.12)',
      borderColor: '#10b981',
      borderWidth: 1.5, borderRadius: 4
    }]
  },
  options: {
    responsive: true, maintainAspectRatio: false,
    plugins: { legend: { display: false } },
    scales: {
      x: { ticks: { autoSkip: false, maxRotation: 30, font: { size: 11, weight: '500' } }, grid: { display: false } },
      y: { beginAtZero: true }
    }
  }
});

// ─── PANEL 2: Tonnage — showing achieved vs target ────────────────────────────
// Completion color scale: red (low %) → green (near/at target) → blue (100%+)
function bucketColor(pct) {
  if (pct === null) return '#94a3b8';
  if (pct >= 100) return '#004df5';
  if (pct >= 90) return '#059669';
  if (pct >= 80) return '#10b981';
  if (pct >= 70) return '#34d399';
  if (pct >= 60) return '#84cc16';
  if (pct >= 50) return '#a3e635';
  if (pct >= 40) return '#eab308';
  if (pct >= 30) return '#f59e0b';
  if (pct >= 20) return '#fb923c';
  if (pct >= 10) return '#f87171';
  return '#ef4444';
}

function fmtKg(v) { return v.toLocaleString('en-IN', { maximumFractionDigits: 0 }); }

const PERIOD_LABELS = {
  full:    'Tonnage achieved vs monthly target — % completion',
  first10: 'First 10 Days — tonnage achieved vs period target',
  mid10:   'Mid 10 Days — tonnage achieved vs period target',
  last10:  'Last 10 Days — tonnage achieved vs period target',
};
const PERIOD_SHORT_LABELS = {
  full: 'Full Month (Till Date)', first10: 'First 10 Days', mid10: 'Mid 10 Days', last10: 'Last 10 Days',
};

let currentPeriod = 'full';

// Pulls the achieved/target pair for a client for whichever period is selected — this single
// filter now drives the client bar list, both charts, and the KAM summary table below.
function getPeriodStats(c, period) {
  if (period === 'full') return { achieved: c.achieved, target: c.target };
  const p = c.periods && c.periods[period];
  return { achieved: p ? p.achieved : null, target: p ? p.target : null };
}

function setTonnagePeriod(period) {
  currentPeriod = period;
  renderTonnageBars();
  renderTonnageCharts();
  renderKamSummary();
}
window.setTonnagePeriod = setTonnagePeriod;

function renderTonnageBars() {
  const barsEl = document.getElementById('tonnage-bars');
  if (!barsEl) return;

  const titleEl = document.getElementById('tonnage-panel-title');
  if (titleEl) titleEl.textContent = PERIOD_LABELS[currentPeriod];

  const withData = clients.map(c => {
    const { achieved, target } = getPeriodStats(c, currentPeriod);
    return { c, achieved, target };
  }).filter(r =>
    (r.achieved !== null && r.achieved !== undefined && r.achieved > 0) ||
    (r.target !== null && r.target !== undefined && r.target > 0)
  );

  withData.sort((a, b) => (b.achieved || b.target || 0) - (a.achieved || a.target || 0));

  if (withData.length === 0) {
    barsEl.innerHTML = `<div class="tonnage-empty">No client data available for the selected period.</div>`;
    return;
  }

  barsEl.innerHTML = withData.map(({ c, achieved, target }) => {
    const hasTarget = target !== null && target !== undefined && target > 0;
    const hasAchieved = achieved !== null && achieved !== undefined && achieved > 0;
    const pct = (hasTarget && hasAchieved) ? Math.round(achieved / target * 100) : null;
    const displayPct = pct !== null ? Math.min(pct, 100) : (hasTarget && !hasAchieved ? 100 : null);
    const barWidth = displayPct !== null ? displayPct + '%' : '100%';
    const barColor = (hasTarget && !hasAchieved) ? '#cbd5e1' : bucketColor(pct);
    const pctLabel = pct !== null ? pct + '%' : '—';
    const newTag = c.isNew ? '<span class="new-tag">New</span>' : '';

    let targetAchieved;
    if (hasTarget && hasAchieved) {
      targetAchieved = `${fmtKg(achieved)} / ${fmtKg(target)} <span style="color:#94a3b8;font-weight:500">kg</span>`;
    } else if (hasTarget && !hasAchieved) {
      targetAchieved = `— / ${fmtKg(target)} <span style="color:#94a3b8;font-weight:500">kg</span> <span style="color:#cbd5e1;font-size:0.65rem">(achieved pending)</span>`;
    } else {
      targetAchieved = `${fmtKg(achieved)} <span style="color:#94a3b8;font-weight:500">kg</span>${currentPeriod !== 'full' ? ' <span style="color:#cbd5e1;font-size:0.65rem">(target pending)</span>' : ''}`;
    }

    return `<div class="client-row">
      <div class="client-name" title="${c.name}"><span class="client-name-text">${c.name}</span>${newTag}</div>
      <div class="client-person">${c.person}</div>
      <div class="prog-bar-wrap">
        <div class="prog-bar" style="width:${barWidth};background:${barColor}"></div>
      </div>
      <div class="pct-text" style="color:${barColor};font-size:0.75rem">${pctLabel}</div>
      <div class="client-tonnage">${targetAchieved}</div>
    </div>`;
  }).join('');
}
window.renderTonnageBars = renderTonnageBars;

// Legend for the completion colour scale
const tonnageLegendEl = document.getElementById('tonnage-legend');
if (tonnageLegendEl) {
  tonnageLegendEl.innerHTML = [
    ['0–40%', '#f59e0b'],
    ['40–70%', '#a3e635'],
    ['70–100%', '#10b981'],
    ['100%+', '#004df5'],
  ].map(([label, color]) => `<span><span class="legend-dot" style="background:${color}"></span>${label}</span>`).join('')
   + `<span><span class="new-tag" style="margin-left:0">New</span> recently onboarded client</span>`;
}

const chartFont = { size: 11, weight: '500' };

// Top clients for the selected period (by achieved, falling back to target if achieved is pending)
function getTopForPeriod(period, n) {
  const rows = clients.map(c => {
    const { achieved, target } = getPeriodStats(c, period);
    return { name: c.name, achieved: achieved || 0, target: target || 0 };
  }).filter(r => r.achieved > 0 || r.target > 0);
  rows.sort((a, b) => (b.achieved || b.target) - (a.achieved || a.target));
  return rows.slice(0, n);
}

let targetChartInstance = null;
let achChartInstance = null;

function renderTonnageCharts() {
  const top8 = getTopForPeriod(currentPeriod, 8);
  const labels = top8.map(r => r.name);
  const periodShort = PERIOD_SHORT_LABELS[currentPeriod];

  if (targetChartInstance) targetChartInstance.destroy();
  targetChartInstance = new Chart(document.getElementById('targetChart'), {
    type: 'bar',
    data: {
      labels,
      datasets: [
        { label: 'Target (kg)', data: top8.map(r => r.target), backgroundColor: 'rgba(0,77,245,0.10)', borderColor: '#004df5', borderWidth: 1.5, borderRadius: 4 },
        { label: 'Achieved (kg)', data: top8.map(r => r.achieved), backgroundColor: 'rgba(16,185,129,0.20)', borderColor: '#10b981', borderWidth: 1.5, borderRadius: 4 }
      ]
    },
    options: {
      indexAxis: 'y', responsive: true, maintainAspectRatio: false,
      plugins: {
        legend: { position: 'bottom', labels: { boxWidth: 12, padding: 16, font: chartFont } },
        title: { display: true, text: `Target vs Achieved — ${periodShort}`, font: { size: 11 }, color: '#94a3b8' }
      },
      scales: {
        x: { beginAtZero: true, ticks: { callback: v => (v/1000).toFixed(0)+'k', font: chartFont } },
        y: { ticks: { font: chartFont }, grid: { display: false } }
      }
    }
  });

  if (achChartInstance) achChartInstance.destroy();
  achChartInstance = new Chart(document.getElementById('achChart'), {
    type: 'bar',
    data: {
      labels,
      datasets: [
        { label: 'Achieved (kg)', data: top8.map(r => r.achieved), backgroundColor: 'rgba(16,185,129,0.15)', borderColor: '#10b981', borderWidth: 1.5, borderRadius: 4 }
      ]
    },
    options: {
      indexAxis: 'y', responsive: true, maintainAspectRatio: false,
      plugins: {
        legend: { position: 'bottom', labels: { boxWidth: 12, padding: 16, font: chartFont } },
        title: { display: true, text: periodShort, font: { size: 11 }, color: '#94a3b8' }
      },
      scales: {
        x: { beginAtZero: true, ticks: { callback: v => (v/1000).toFixed(0)+'k', font: chartFont } },
        y: { ticks: { font: chartFont }, grid: { display: false } }
      }
    }
  });
}
window.renderTonnageCharts = renderTonnageCharts;

// ─── PANEL 3: Daily Average Table ─────────────────────────────────────────────
const tbody = document.getElementById('daily-table-body');
if (tbody) {
  clients.filter(c => c.achieved > 0).forEach(c => {
    const pct      = c.target > 0 ? Math.round(c.achieved / c.target * 100) + '%' : '—';
    const pctColor = c.target > 0 ? (c.achieved >= c.target ? '#10b981' : '#004df5') : '#94a3b8';
    const remaining = c.target > 0 ? Math.max(c.target - c.achieved, 0).toLocaleString('en-IN') : '—';
    const daysToFinish = c.target > 0 && c.avgDay > 0 && c.remaining > 0
      ? parseFloat((c.remaining / c.avgDay).toFixed(1))
      : (c.target > 0 && c.remaining === 0 ? '✓' : '—');
    const targetDisplay = c.target > 0 ? c.target.toLocaleString('en-IN') : '—';
    tbody.innerHTML += `<tr>
      <td style="font-weight:600">${c.name}</td>
      <td style="font-size:0.8rem;color:#64748b">${c.person}</td>
      <td>${targetDisplay}</td>
      <td>${c.achieved.toLocaleString('en-IN')}</td>
      <td style="color:${pctColor};font-weight:700">${pct}</td>
      <td>${c.activeDays}</td>
      <td>${c.avgDay.toLocaleString('en-IN')}</td>
      <td style="color:#f59e0b">${remaining}</td>
      <td style="color:#ef4444">${daysToFinish}</td>
    </tr>`;
  });
}

// ─── CHART 7: Avg kg/day ──────────────────────────────────────────────────────
const topAvg = clients.filter(c => c.avgDay > 0).sort((a, b) => b.avgDay - a.avgDay).slice(0, 10);
new Chart(document.getElementById('avgDayChart'), {
  type: 'bar',
  data: {
    labels: topAvg.map(c => c.name),
    datasets: [{ label: 'Avg kg/day', data: topAvg.map(c => c.avgDay), backgroundColor: 'rgba(99,102,241,0.12)', borderColor: '#6366f1', borderWidth: 1.5, borderRadius: 4 }]
  },
  options: {
    indexAxis: 'y', responsive: true, maintainAspectRatio: false,
    plugins: { legend: { display: false } },
    scales: {
      x: { beginAtZero: true, ticks: { callback: v => v.toLocaleString('en-IN'), font: chartFont } },
      y: { ticks: { font: chartFont }, grid: { display: false } }
    }
  }
});

// ─── CHART 8: Days to Complete ────────────────────────────────────────────────
const daysChartEl = document.getElementById('daysChart');
if (daysChartEl) {
  const daysData = clients.filter(c => c.target > 0 && c.avgDay > 0 && c.remaining > 0)
    .sort((a, b) => b.daysNeeded - a.daysNeeded).slice(0, 10);
  new Chart(daysChartEl, {
    type: 'bar',
    data: {
      labels: daysData.map(c => c.name),
      datasets: [{
        label: 'Days to finish remaining target',
        data: daysData.map(c => c.daysNeeded),
        backgroundColor: daysData.map(c => c.daysNeeded > 18 ? 'rgba(239,68,68,0.18)' : 'rgba(245,158,11,0.18)'),
        borderColor: daysData.map(c => c.daysNeeded > 18 ? '#ef4444' : '#f59e0b'),
        borderWidth: 1.5, borderRadius: 4
      }]
    },
    options: {
      indexAxis: 'y', responsive: true, maintainAspectRatio: false,
      plugins: {
        legend: { display: false },
        title: { display: true, text: 'Estimated days to finish at current avg rate', font: { size: 11 }, color: '#94a3b8' }
      },
      scales: {
        x: { beginAtZero: true, ticks: { font: chartFont } },
        y: { ticks: { font: chartFont }, grid: { display: false } }
      }
    }
  });
}

// ─── PANEL 4: KAM-wise breakdown — merged into the Tonnage panel, period-aware ────
// Shows KAM name + total target + total achieved + % done for whichever period is selected.
// Clients with no target/achieved for a period contribute 0 to that period's KAM totals.
function renderKamSummary() {
  const body = document.getElementById('kam-summary-body');
  if (!body) return;

  const kamMap = {};
  clients.forEach(c => {
    const { achieved, target } = getPeriodStats(c, currentPeriod);
    if (!achieved && !target) return;
    if (!kamMap[c.person]) kamMap[c.person] = { person: c.person, totalTarget: 0, totalAchieved: 0 };
    kamMap[c.person].totalTarget += (target || 0);
    kamMap[c.person].totalAchieved += (achieved || 0);
  });
  const kamList = Object.values(kamMap).sort((a, b) => b.totalAchieved - a.totalAchieved);

  if (kamList.length === 0) {
    body.innerHTML = `<tr><td colspan="4" style="text-align:center;color:#94a3b8;padding:20px">No KAM data available for the selected period.</td></tr>`;
    return;
  }

  body.innerHTML = kamList.map(k => {
    const pct = k.totalTarget > 0 ? Math.round(k.totalAchieved / k.totalTarget * 100) : null;
    const pctColor = pct === null ? '#94a3b8' : bucketColor(pct);
    return `<tr>
      <td style="font-weight:700">${k.person}</td>
      <td>${k.totalTarget > 0 ? fmtKg(k.totalTarget) : '—'}</td>
      <td>${fmtKg(k.totalAchieved)}</td>
      <td style="color:${pctColor};font-weight:700">${pct !== null ? pct + '%' : '—'}</td>
    </tr>`;
  }).join('');
}
window.renderKamSummary = renderKamSummary;

// Initial render for the whole period-driven Tonnage panel
renderTonnageBars();
renderTonnageCharts();
renderKamSummary();
